-- ============================================================================
-- FASE 7: CARGAR TODAS LAS FORMULAS MAESTRAS CON CODIGOS MPMP
-- ============================================================================
-- Método: JOINs automáticos por nombre de producto y código de material MPMP
-- Estructura: INSERT SELECT con VALUES + JOINs a tablas materiales y productos
-- ============================================================================

INSERT INTO formulas (producto_id, material_id, cantidad_por_unidad, unidad)
SELECT
  p.id AS producto_id,
  m.id AS material_id,
  formulas_data.cantidad,
  'g' AS unidad
FROM (
  VALUES
  -- AZ HIBRID CLEAR
  ('AZ HIBRID CLEAR', 'MPMP00037', 2.0),    -- ACIDO SALICILICO
  ('AZ HIBRID CLEAR', 'MPMP00017', 3.0),    -- ACIDO ASCORBICO
  ('AZ HIBRID CLEAR', 'MPMP00018', 1.5),    -- ACIDO AZELAICO
  ('AZ HIBRID CLEAR', 'MPMP00050', 5.0),    -- ALOE VERA
  ('AZ HIBRID CLEAR', 'MPMP00100', 10.0),   -- GLICERINA
  ('AZ HIBRID CLEAR', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('AZ HIBRID CLEAR', 'MPMP00041', 78.0),   -- AGUA DESIONIZADA
  
  -- CONTORNO DE CAFEINA
  ('CONTORNO DE CAFEINA', 'MPMP00074', 5.0),    -- CAFEINA
  ('CONTORNO DE CAFEINA', 'MPMP00032', 3.0),    -- ACIDO HIALURÓNICO 300 KD
  ('CONTORNO DE CAFEINA', 'MPMP00120', 2.0),    -- LAURIL GLUCOSIDO
  ('CONTORNO DE CAFEINA', 'MPMP00100', 15.0),   -- GLICERINA
  ('CONTORNO DE CAFEINA', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('CONTORNO DE CAFEINA', 'MPMP00041', 74.5),   -- AGUA DESIONIZADA
  
  -- CONTORNO DE OJOS MULTIPEPTIDOS
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00145', 2.5),   -- PALMITOYL TRIPEPTIDE 1
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00143', 2.0),   -- PALMITOYL TETRAPEPTIDE-7
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00147', 1.5),   -- PALMITOYL TRIPEPTIDE-1
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00032', 4.0),   -- ACIDO HIALURÓNICO 300 KD
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00100', 12.0),  -- GLICERINA
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('CONTORNO DE OJOS MULTIPEPTIDOS', 'MPMP00041', 77.5),  -- AGUA DESIONIZADA
  
  -- CONTORNO DE OJOS RETINALDEHIDO
  ('CONTORNO DE OJOS RETINALDEHIDO', 'MPMP00170', 0.3),   -- RETINALDEHIDO
  ('CONTORNO DE OJOS RETINALDEHIDO', 'MPMP00032', 3.0),   -- ACIDO HIALURÓNICO 300 KD
  ('CONTORNO DE OJOS RETINALDEHIDO', 'MPMP00100', 12.0),  -- GLICERINA
  ('CONTORNO DE OJOS RETINALDEHIDO', 'MPMP00121', 1.0),   -- LAURYL GLUCOSIDE
  ('CONTORNO DE OJOS RETINALDEHIDO', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('CONTORNO DE OJOS RETINALDEHIDO', 'MPMP00041', 83.2),  -- AGUA DESIONIZADA
  
  -- CREMA CORPORAL RENOVA BODY
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00036', 3.0),    -- ACIDO LACTICO
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00034', 2.0),    -- ACIDO HILAURONICO 50 KD
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00004', 5.0),    -- ACEITE DE ARGAN
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00100', 20.0),   -- GLICERINA
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00044', 10.0),   -- ALCOHOL CETILICO
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00093', 0.8),    -- FENOXIETANOL
  ('CREMA CORPORAL RENOVA BODY', 'MPMP00041', 59.2),   -- AGUA DESIONIZADA
  
  -- CREMA DE UREA
  ('CREMA DE UREA', 'MPMP00212', 10.0),   -- ÚREA
  ('CREMA DE UREA', 'MPMP00100', 15.0),   -- GLICERINA
  ('CREMA DE UREA', 'MPMP00004', 5.0),    -- ACEITE DE ARGAN
  ('CREMA DE UREA', 'MPMP00093', 0.8),    -- FENOXIETANOL
  ('CREMA DE UREA', 'MPMP00041', 69.2),   -- AGUA DESIONIZADA
  
  -- EMULSION HIDRATANTE B3+BHA
  ('EMULSION HIDRATANTE B3+BHA', 'MPMP00134', 5.0),    -- NIACINAMIDA
  ('EMULSION HIDRATANTE B3+BHA', 'MPMP00037', 2.0),    -- ACIDO SALICILICO
  ('EMULSION HIDRATANTE B3+BHA', 'MPMP00032', 3.0),    -- ACIDO HIALURÓNICO 300 KD
  ('EMULSION HIDRATANTE B3+BHA', 'MPMP00100', 12.0),   -- GLICERINA
  ('EMULSION HIDRATANTE B3+BHA', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('EMULSION HIDRATANTE B3+BHA', 'MPMP00041', 77.5),   -- AGUA DESIONIZADA
  
  -- EMULSION LIMPIADORA
  ('EMULSION LIMPIADORA', 'MPMP00120', 3.0),   -- LAURIL GLUCOSIDO
  ('EMULSION LIMPIADORA', 'MPMP00100', 10.0),  -- GLICERINA
  ('EMULSION LIMPIADORA', 'MPMP00093', 1.0),   -- FENOXIETANOL
  ('EMULSION LIMPIADORA', 'MPMP00041', 86.0),  -- AGUA DESIONIZADA
  
  -- ESENCIA CENTELLA ASIATICA
  ('ESENCIA CENTELLA ASIATICA', 'MPMP00077', 10.0),  -- CENTELLA
  ('ESENCIA CENTELLA ASIATICA', 'MPMP00100', 15.0),  -- GLICERINA
  ('ESENCIA CENTELLA ASIATICA', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('ESENCIA CENTELLA ASIATICA', 'MPMP00041', 74.5),  -- AGUA DESIONIZADA
  
  -- ESENCIA ILUMINADORA
  ('ESENCIA ILUMINADORA', 'MPMP00035', 2.0),   -- ACIDO KOJICO
  ('ESENCIA ILUMINADORA', 'MPMP00047', 5.0),   -- ALFA ARBUTINA
  ('ESENCIA ILUMINADORA', 'MPMP00100', 15.0),  -- GLICERINA
  ('ESENCIA ILUMINADORA', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('ESENCIA ILUMINADORA', 'MPMP00041', 77.5),  -- AGUA DESIONIZADA
  
  -- GEL HIDRATANTE
  ('GEL HIDRATANTE', 'MPMP00032', 5.0),    -- ACIDO HIALURÓNICO 300 KD
  ('GEL HIDRATANTE', 'MPMP00108', 2.0),    -- GOMA XANTAN
  ('GEL HIDRATANTE', 'MPMP00100', 10.0),   -- GLICERINA
  ('GEL HIDRATANTE', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('GEL HIDRATANTE', 'MPMP00041', 82.5),   -- AGUA DESIONIZADA
  
  -- LIMPIADOR FACIAL BHA 2%
  ('LIMPIADOR FACIAL BHA 2%', 'MPMP00037', 2.0),    -- ACIDO SALICILICO
  ('LIMPIADOR FACIAL BHA 2%', 'MPMP00120', 2.0),    -- LAURIL GLUCOSIDO
  ('LIMPIADOR FACIAL BHA 2%', 'MPMP00093', 1.0),    -- FENOXIETANOL
  ('LIMPIADOR FACIAL BHA 2%', 'MPMP00041', 95.0),   -- AGUA DESIONIZADA
  
  -- LIMPIADOR FACIAL HIDRATANTE
  ('LIMPIADOR FACIAL HIDRATANTE', 'MPMP00120', 3.0),   -- LAURIL GLUCOSIDO
  ('LIMPIADOR FACIAL HIDRATANTE', 'MPMP00100', 5.0),   -- GLICERINA
  ('LIMPIADOR FACIAL HIDRATANTE', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('LIMPIADOR FACIAL HIDRATANTE', 'MPMP00041', 91.5),  -- AGUA DESIONIZADA
  
  -- LIMPIADOR ILUMINADOR ACIDO KOJICO
  ('LIMPIADOR ILUMINADOR ACIDO KOJICO', 'MPMP00035', 2.0),   -- ACIDO KOJICO
  ('LIMPIADOR ILUMINADOR ACIDO KOJICO', 'MPMP00120', 2.0),   -- LAURIL GLUCOSIDO
  ('LIMPIADOR ILUMINADOR ACIDO KOJICO', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('LIMPIADOR ILUMINADOR ACIDO KOJICO', 'MPMP00041', 95.5),  -- AGUA DESIONIZADA
  
  -- LIMPIADOR ILUMINADOR KOJICO
  ('LIMPIADOR ILUMINADOR KOJICO', 'MPMP00035', 2.0),   -- ACIDO KOJICO
  ('LIMPIADOR ILUMINADOR KOJICO', 'MPMP00120', 2.0),   -- LAURIL GLUCOSIDO
  ('LIMPIADOR ILUMINADOR KOJICO', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('LIMPIADOR ILUMINADOR KOJICO', 'MPMP00041', 95.5),  -- AGUA DESIONIZADA
  
  -- MAXLASH
  ('MAXLASH', 'MPMP00001', 15.5),    -- 1,2 HEXANEDIOL
  ('MAXLASH', 'MPMP00009', 5.0),     -- ACETYL HEXAPEPTIDE-8
  ('MAXLASH', 'MPMP00133', 2.5),     -- NAD
  ('MAXLASH', 'MPMP00100', 20.0),    -- GLICERINA
  ('MAXLASH', 'MPMP00093', 0.5),     -- FENOXIETANOL
  ('MAXLASH', 'MPMP00041', 56.5),    -- AGUA DESIONIZADA
  
  -- SUERO ANTIOXIDANTE RENOVA C10
  ('SUERO ANTIOXIDANTE RENOVA C10', 'MPMP00017', 10.0),   -- ACIDO ASCORBICO
  ('SUERO ANTIOXIDANTE RENOVA C10', 'MPMP00202', 2.0),    -- ÁCIDO FERÚLICO
  ('SUERO ANTIOXIDANTE RENOVA C10', 'MPMP00199', 5.0),    -- VITAMINA E POLVO
  ('SUERO ANTIOXIDANTE RENOVA C10', 'MPMP00100', 10.0),   -- GLICERINA
  ('SUERO ANTIOXIDANTE RENOVA C10', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('SUERO ANTIOXIDANTE RENOVA C10', 'MPMP00041', 72.5),   -- AGUA DESIONIZADA
  
  -- SUERO ANTIOXIDANTE VITAMINA C+B3
  ('SUERO ANTIOXIDANTE VITAMINA C+B3', 'MPMP00017', 8.0),    -- ACIDO ASCORBICO
  ('SUERO ANTIOXIDANTE VITAMINA C+B3', 'MPMP00134', 5.0),    -- NIACINAMIDA
  ('SUERO ANTIOXIDANTE VITAMINA C+B3', 'MPMP00100', 10.0),   -- GLICERINA
  ('SUERO ANTIOXIDANTE VITAMINA C+B3', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('SUERO ANTIOXIDANTE VITAMINA C+B3', 'MPMP00041', 76.5),   -- AGUA DESIONIZADA
  
  -- SUERO EXFOLIANTE BHA 2%
  ('SUERO EXFOLIANTE BHA 2%', 'MPMP00037', 2.0),    -- ACIDO SALICILICO
  ('SUERO EXFOLIANTE BHA 2%', 'MPMP00100', 10.0),   -- GLICERINA
  ('SUERO EXFOLIANTE BHA 2%', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('SUERO EXFOLIANTE BHA 2%', 'MPMP00041', 87.5),   -- AGUA DESIONIZADA
  
  -- SUERO EXFOLIANTE NOVA PHA
  ('SUERO EXFOLIANTE NOVA PHA', 'MPMP00103', 3.0),   -- GLUCONOLACTONA
  ('SUERO EXFOLIANTE NOVA PHA', 'MPMP00100', 10.0),  -- GLICERINA
  ('SUERO EXFOLIANTE NOVA PHA', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('SUERO EXFOLIANTE NOVA PHA', 'MPMP00041', 86.5),  -- AGUA DESIONIZADA
  
  -- SUERO HIDRATANTE ACIDO HIALURONICO 1.5%
  ('SUERO HIDRATANTE ACIDO HIALURONICO 1.5%', 'MPMP00032', 1.5),   -- ACIDO HIALURÓNICO 300 KD
  ('SUERO HIDRATANTE ACIDO HIALURONICO 1.5%', 'MPMP00100', 15.0),  -- GLICERINA
  ('SUERO HIDRATANTE ACIDO HIALURONICO 1.5%', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('SUERO HIDRATANTE ACIDO HIALURONICO 1.5%', 'MPMP00041', 82.0),  -- AGUA DESIONIZADA
  
  -- SUERO ILUMINADOR TRX
  ('SUERO ILUMINADOR TRX', 'MPMP00047', 5.0),   -- ALFA ARBUTINA
  ('SUERO ILUMINADOR TRX', 'MPMP00143', 2.0),   -- PALMITOYL TETRAPEPTIDE-7
  ('SUERO ILUMINADOR TRX', 'MPMP00100', 10.0),  -- GLICERINA
  ('SUERO ILUMINADOR TRX', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('SUERO ILUMINADOR TRX', 'MPMP00041', 82.5),  -- AGUA DESIONIZADA
  
  -- SUERO MULTIPEPTIDOS
  ('SUERO MULTIPEPTIDOS', 'MPMP00159', 5.0),    -- PEPTIDOS DE COLAGENO
  ('SUERO MULTIPEPTIDOS', 'MPMP00143', 2.0),    -- PALMITOYL TETRAPEPTIDE-7
  ('SUERO MULTIPEPTIDOS', 'MPMP00032', 2.0),    -- ACIDO HIALURÓNICO 300 KD
  ('SUERO MULTIPEPTIDOS', 'MPMP00100', 10.0),   -- GLICERINA
  ('SUERO MULTIPEPTIDOS', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('SUERO MULTIPEPTIDOS', 'MPMP00041', 80.5),   -- AGUA DESIONIZADA
  
  -- SUERO NIACINAMIDA 5%
  ('SUERO NIACINAMIDA 5%', 'MPMP00134', 5.0),   -- NIACINAMIDA
  ('SUERO NIACINAMIDA 5%', 'MPMP00100', 10.0),  -- GLICERINA
  ('SUERO NIACINAMIDA 5%', 'MPMP00093', 0.5),   -- FENOXIETANOL
  ('SUERO NIACINAMIDA 5%', 'MPMP00041', 84.5),  -- AGUA DESIONIZADA
  
  -- SUERO VITAMINA C+
  ('SUERO VITAMINA C+', 'MPMP00017', 10.0),   -- ACIDO ASCORBICO
  ('SUERO VITAMINA C+', 'MPMP00199', 5.0),    -- VITAMINA E POLVO
  ('SUERO VITAMINA C+', 'MPMP00100', 10.0),   -- GLICERINA
  ('SUERO VITAMINA C+', 'MPMP00093', 0.5),    -- FENOXIETANOL
  ('SUERO VITAMINA C+', 'MPMP00041', 74.5)    -- AGUA DESIONIZADA
) AS formulas_data(producto_nombre, material_codigo, cantidad)
JOIN productos p ON UPPER(p.nombre) = formulas_data.producto_nombre
JOIN materiales m ON m.codigo = formulas_data.material_codigo;

-- ============================================================================
-- VALIDACIÓN POST-CARGA (ejecutar después de INSERT)
-- ============================================================================
-- SELECT COUNT(*) as total_formulas FROM formulas;
-- SELECT DISTINCT nombre FROM productos WHERE id IN (SELECT DISTINCT producto_id FROM formulas) ORDER BY nombre;
-- SELECT COUNT(DISTINCT material_id) FROM formulas;
-- ============================================================================
