"""Fase 2 migracion PG · traduce el esquema SQLite a DDL PostgreSQL.

Lee el volcado de dump_sqlite_schema.py y produce:
  - pg_schema.sql        · tablas + claves foraneas (ALTER) + indices
  - triggers_to_port.sql · los 42 triggers SQLite crudos (se portan a
                           plpgsql a mano)

Reglas:
  INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
  REAL                  -> DOUBLE PRECISION
  DATETIME (tipo)       -> TEXT  (EOS guarda timestamps como string)
  datetime('now'[,utc]) -> to_char(...) formato SQLite
  date('now')           -> to_char(now(),'YYYY-MM-DD')
  date(columna)         -> substr(columna,1,10)  (date() no es IMMUTABLE en PG)

Las FOREIGN KEY se sacan del CREATE TABLE y se emiten como ALTER TABLE
DESPUES de crear todas las tablas · asi el orden alfabetico no rompe las
referencias.

Uso:  python scripts/translate_schema_to_pg.py
"""
import re

SRC = 'C:/Users/sebas/pgdev/sqlite_schema_actual.sql'
OUT_SCHEMA = 'C:/Users/sebas/pgdev/pg_schema.sql'
OUT_TRIGGERS = 'C:/Users/sebas/pgdev/triggers_to_port.sql'

_FK = re.compile(
    r',?\s*FOREIGN\s+KEY\s*\(([^)]*)\)\s*REFERENCES\s+(\w+)\s*\(([^)]*)\)'
    r'((?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|SET\s+NULL|SET\s+DEFAULT|'
    r'RESTRICT|NO\s+ACTION))*)',
    re.I,
)


def traducir(ddl: str) -> str:
    s = ddl
    s = re.sub(r'INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT',
               'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
               s, flags=re.I)
    s = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', s)
    s = re.sub(r'\bDATETIME\b', 'TEXT', s)
    # fechas · primero los literales 'now', luego date(columna)
    s = re.sub(r"datetime\(\s*'now'\s*,\s*'utc'\s*\)",
               "to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')",
               s, flags=re.I)
    s = re.sub(r"datetime\(\s*'now'\s*\)",
               "to_char(now(),'YYYY-MM-DD HH24:MI:SS')", s, flags=re.I)
    s = re.sub(r"date\(\s*'now'\s*\)",
               "to_char(now(),'YYYY-MM-DD')", s, flags=re.I)
    # date(columna) -> substr(columna,1,10) · date() sobre texto no es
    # IMMUTABLE y Postgres lo rechaza en indices.
    s = re.sub(r"\bdate\(\s*([a-z_][a-z0-9_]*)\s*\)",
               r"substr(\1,1,10)", s, flags=re.I)
    return s


def extraer_fks(tabla: str, ddl: str):
    """Saca las FOREIGN KEY del CREATE TABLE · devuelve (ddl_sin_fk, [alters])."""
    alters = []

    def _repl(m):
        cols, reftbl, refcols, acciones = (m.group(1).strip(), m.group(2),
                                           m.group(3).strip(), m.group(4))
        alters.append(
            f"ALTER TABLE {tabla} ADD FOREIGN KEY ({cols}) "
            f"REFERENCES {reftbl} ({refcols}){acciones};")
        return ''

    nuevo = _FK.sub(_repl, ddl)
    # limpiar comas colgantes que deja el borrado de las FK
    nuevo = re.sub(r',(\s*,)+', ',', nuevo)
    nuevo = re.sub(r',\s*\)', '\n)', nuevo)
    return nuevo, alters


def main():
    with open(SRC, encoding='utf-8') as f:
        contenido = f.read()

    bloques = re.split(r'^-- \[(table|index|trigger)\] (.+)$',
                       contenido, flags=re.M)
    tablas, fks, indices, triggers = [], [], [], []
    i = 1
    while i + 2 <= len(bloques) - 1:
        tipo, nombre, sql = bloques[i], bloques[i + 1].strip(), bloques[i + 2].strip()
        if sql.endswith(';'):
            sql = sql[:-1].rstrip()
        if tipo == 'table':
            ddl = traducir(sql)
            ddl, alters = extraer_fks(nombre, ddl)
            tablas.append((nombre, ddl))
            fks.extend(alters)
        elif tipo == 'index':
            indices.append((nombre, traducir(sql)))
        elif tipo == 'trigger':
            triggers.append((nombre, sql))
        i += 3

    with open(OUT_SCHEMA, 'w', encoding='utf-8') as f:
        f.write('-- Esquema PostgreSQL de EOS · generado por translate_schema_to_pg.py\n')
        f.write(f'-- {len(tablas)} tablas, {len(fks)} FK, {len(indices)} indices\n\n')
        for nombre, sql in tablas:
            f.write(f'-- tabla: {nombre}\n{sql};\n\n')
        f.write('\n-- ===== CLAVES FORANEAS =====\n\n')
        for a in fks:
            f.write(a + '\n')
        f.write('\n-- ===== INDICES =====\n\n')
        for nombre, sql in indices:
            f.write(f'{sql};\n')

    with open(OUT_TRIGGERS, 'w', encoding='utf-8') as f:
        f.write(f'-- {len(triggers)} triggers SQLite · portar a plpgsql a mano\n\n')
        for nombre, sql in triggers:
            f.write(f'-- [trigger] {nombre}\n{sql};\n\n')

    print(f'OK · {len(tablas)} tablas, {len(fks)} FK, {len(indices)} indices '
          f'-> pg_schema.sql')
    print(f'     {len(triggers)} triggers -> triggers_to_port.sql')


if __name__ == '__main__':
    main()
