-- =====================================================================
-- Correcciones masivas formula_items + maestro_mps
-- Fecha: 2026-04-28
-- Ejecutar: BEGIN ... COMMIT (transaccion atomica)
-- VERIFICAR ANTES: SELECT codigo_mp FROM maestro_mps WHERE codigo_mp >= 'MP00400' AND codigo_mp <= 'MP00500';
--                  Si hay codigos ocupados en ese rango, ajustar START_CODE
-- =====================================================================

BEGIN TRANSACTION;

-- 1) BACKUP automatico
CREATE TABLE IF NOT EXISTS formula_items_backup_20260428 AS SELECT * FROM formula_items;
CREATE TABLE IF NOT EXISTS maestro_mps_backup_20260428 AS SELECT * FROM maestro_mps;

-- 2) INSERT nuevos MPs (44)
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00400', '1,2-Hexanediol', '1,2-Hexanediol', 'Conservante boost', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00401', 'Argania Spinosa Kernel Oil', 'Aceite de argan', 'Aceite vegetal', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00402', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'Aceite de jojoba', 'Aceite vegetal', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00403', 'Acetyl Tetrapeptide-40', 'Acetil tetrapeptido-40', 'Peptido', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00404', 'Capryloyl Salicylic Acid', 'LHA', 'Exfoliante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00405', 'Sodium Hyaluronate (HMW 1500 kDa)', 'AH 1500 kDa', 'Hidratante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00406', 'Sodium Hyaluronate (MMW 300 kDa)', 'AH 300 kDa', 'Hidratante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00407', 'Dibutyl Adipate', 'Cetiol B', 'Emoliente', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00408', 'Cetyl Alcohol', 'Alcohol cetilico', 'Espesante graso', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00409', 'Tetrahexyldecyl Ascorbate', 'THD ascorbato', 'Vit C liposoluble', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00410', 'Ascorbyl Glucoside', 'Ascorbil glucosido', 'Vit C', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00411', 'Asiaticoside', 'Asiaticosido (puro)', 'Cicatrizante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00412', 'Potassium Azeloyl Diglycinate', 'Azelolil diglicinato K', 'Anti-acne', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00413', 'Beta-Cyclodextrin', 'Beta-ciclodextrina', 'Encapsulante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00414', 'Ceramide NP', 'Ceramida NP', 'Barrera', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00415', 'Cetyl Tranexamate Mesylate', 'CTM (Sepiwhite MSH)', 'Despigmentante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00416', 'Dicaprylyl Carbonate', 'Cetiol CC', 'Emoliente', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00417', 'Dipeptide Diaminobutyroyl Benzylamide Diacetate', 'Syn-Ake', 'Peptido', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00418', 'Squalane', 'Escualano', 'Aceite/Emoliente', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00419', 'Trifolium Pratense Extract', 'Extracto trebol rojo', 'Fitoestrogeno', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00420', 'Sodium Phytate', 'Fitato de sodio', 'Quelante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00421', 'Sodium Ascorbyl Phosphate', 'SAP', 'Vit C', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00422', 'Fragrance', 'Fragancia fresa cremoso', 'Fragancia', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00423', 'Sodium Hydroxide', 'Soda caustica', 'Ajuste pH', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00424', 'Hydroxypinacolone Retinoate', 'HPR / Granactive Retinoid', 'Retinoide', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00425', 'Ergothioneine', 'L-Ergotioneina', 'Antioxidante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00426', 'Methylsulfonylmethane', 'MSM', 'Anti-inflamatorio', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00427', 'Nicotinamide Adenine Dinucleotide', 'NAD+', 'Antiage cellular', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00428', 'Boron Nitride', 'Nitruro de boro', 'Soft focus', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00429', 'Oligopeptide-68', 'Oligopeptido-68', 'Peptido despigmentante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00430', 'Isopropyl Palmitate', 'Palmitato de isopropilo', 'Emoliente', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00431', 'Palmitoyl Tripeptide-38', 'Palmitoil tripeptido-38', 'Peptido', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00432', 'Panthenol', 'Pantenol liquido (Provitamina B5)', 'Hidratante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00433', 'PEG-12 Dimethicone', 'PEG-12 dimeticona', 'Silicona', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00434', 'Hydrolyzed Keratin', 'Peptidos hidrolizados queratina', 'Proteina', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00435', 'Propanediol', 'Propanediol PDO', 'Humectante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00436', 'QUIMCREAM', 'QUIMCREAM (proveedor)', 'Emulsificante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00437', 'Resveratrol', 'Resveratrol', 'Antioxidante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00438', 'Retinyl Retinoate', 'Retinil retinoato (RR)', 'Retinoide', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00439', 'Dimethicone', 'Silicona liquida', 'Silicona', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00440', 'Sodium Tocopheryl Phosphate', 'Vit E hidrosoluble', 'Vit E', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00441', 'Centella Asiatica Triterpenes 98%', 'Terpenos solubles 98%', 'Activo botanico', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00442', 'Undecylenoyl Phenylalanine', 'Sepiwhite MSH', 'Despigmentante', 1);
INSERT OR IGNORE INTO maestro_mps (codigo_mp, nombre_inci, nombre_comercial, tipo, activo) VALUES ('MP00443', 'Ferulic Acid', 'Acido ferulico', 'Antioxidante', 1);

-- 3) Marcar AZECLAIR (MP00284) como inactivo (no se usa)
UPDATE maestro_mps SET activo=0 WHERE codigo_mp='MP00284';

-- 4) Actualizar nombre INCI de AOS 40 (MP00212) con INCI oficial
UPDATE maestro_mps SET nombre_inci='Sodium C14-16 Olefin Sulfonate' WHERE codigo_mp='MP00212';

-- 5) UPDATEs formula_items (correcciones)
UPDATE formula_items SET material_id='MP00400', material_nombre='1,2-Hexanediol' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='1,2 HEXANEDIOL' AND material_id='MPHEXDILI01';
UPDATE formula_items SET material_id='MP00404', material_nombre='LHA' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='ACIDO CAPRILOIL SALICILICO' AND material_id='MPACCASAS01';
UPDATE formula_items SET material_id='MP00412', material_nombre='Azelolil diglicinato K' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='AZELOLIL DIGLICINATO DE POTASIO' AND material_id='MPAZDISO01';
UPDATE formula_items SET material_id='MP00226', material_nombre='Ectoin' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='ECTOINA' AND material_id='MPECTOSO01';
UPDATE formula_items SET material_id='MP00116', material_nombre='Epi-On' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='EPI-ON (AZELAMIDOPROPIL DIMETIL AMINA)' AND material_id='MPAZEDILO01';
UPDATE formula_items SET material_id='MP00420', material_nombre='Fitato de sodio' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='FITATO DE SODIO' AND material_id='MPFISOSO01';
UPDATE formula_items SET material_id='MP00421', material_nombre='SAP' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='FOSFATO DE ASCORBILO SODICO' AND material_id='MPFOASSO01';
UPDATE formula_items SET material_id='MP00073', material_nombre='Goma xanthan' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='GOMA XANTAN' AND material_id='MPGOXASO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='GRANSIL VX419' AND material_id='MPGRANLI01';
UPDATE formula_items SET material_id='MP00423', material_nombre='Soda caustica' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='HIDROXIDO DE SODIO (SODA CAUSTICA)' AND material_id='MPHIDSOLI01';
UPDATE formula_items SET material_id='MP00176', material_nombre='Centella asiatica triterpenes 80%' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='TERPENOS SOLUBLES 80%' AND material_id='MPTERSSO01';
UPDATE formula_items SET material_id='MP00123', material_nombre='Trietanolamina' WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='TRIETANOLAMINA 85%' AND material_id='MPTRIELO01';
UPDATE formula_items SET material_id='MP00175', material_nombre='Acetyl tetrapeptide-5' WHERE producto_nombre='CONTORNO DE CAFEINA' AND material_nombre='ACETYL TETRAPETIDE-5' AND material_id='MPACTESO01';
UPDATE formula_items SET material_id='MP00163', material_nombre='Ácido hialurónico 50 kD' WHERE producto_nombre='CONTORNO DE CAFEINA' AND material_nombre='ACIDO HIALURONICO 50KD' AND material_id='MPACHISO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='CONTORNO DE CAFEINA' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00410', material_nombre='Ascorbil glucosido' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='ASCORBIL GLUCOSIDE' AND material_id='MPASGLSO01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00194', material_nombre='Copper tripeptide-1' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='COOPER TRIPEPTIDE-1' AND material_id='MPCOTRSO01';
UPDATE formula_items SET material_id='MP00172', material_nombre='Palmitoyl tetrapeptide-7' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='PALMIYOL TETRAPEPTIDE-7' AND material_id='MPPALTESO01';
UPDATE formula_items SET material_id='MP00190', material_nombre='Palmitoyl tripeptide-1' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='PALMIYOL TRIPEPTIDE-1' AND material_id='MPPALTRISO02';
UPDATE formula_items SET material_id='MP00191', material_nombre='Palmitoyl tripeptide-5' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='PALMIYOL TRIPEPTIDE-5' AND material_id='MPPALTRISO01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='PEPTIDOS DE COLAGENO POLVO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00123', material_nombre='Trietanolamina' WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='TRIETANOLAMINA 85%' AND material_id='MPTRIESO01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='CONTORNO DE OJOS RETINALDEHIDO 0.05%' AND material_nombre='BETAGLUCAM' AND material_id='MPBETASO02';
UPDATE formula_items SET material_id='MP00418', material_nombre='Escualano' WHERE producto_nombre='CONTORNO DE OJOS RETINALDEHIDO 0.05%' AND material_nombre='ESCUALENO' AND material_id='MPESCULI01';
UPDATE formula_items SET material_id='MP00262', material_nombre='N-acetil glucosamina' WHERE producto_nombre='CONTORNO DE OJOS RETINALDEHIDO 0.05%' AND material_nombre='N-ACETILGLUCOSAMINA' AND material_id='MPGLUCSO01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='CONTORNO DE OJOS RETINALDEHIDO 0.05%' AND material_nombre='PEPTIDOS DE COLAGENO POLVO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='CONTORNO DE OJOS RETINALDEHIDO 0.05%' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00401', material_nombre='Aceite de argan' WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='ACEITE DE ARGAN' AND material_id='MPACARLI01';
UPDATE formula_items SET material_id='MP00402', material_nombre='Aceite de jojoba' WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='ACEITE DE JOJOBA' AND material_id='MPACJOLI01';
UPDATE formula_items SET material_id='MP00407', material_nombre='Cetiol B' WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='ADIPATO DE BUTIL' AND material_id='MPDIADI01';
UPDATE formula_items SET material_id='MP00020', material_nombre='Yogurt cremoso' WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='FRAGANCIA YOGURT CREMOSO' AND material_id='MPYOCRLI01';
UPDATE formula_items SET material_id='MP00430', material_nombre='Palmitato de isopropilo' WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='PALMITATO DE ISOPROPILO' AND material_id='MPPALISO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00402', material_nombre='Aceite de jojoba' WHERE producto_nombre='CREMA DE UREA' AND material_nombre='ACEITE DE JOJOBA' AND material_id='MPACJOLI01';
UPDATE formula_items SET material_id='MP00432', material_nombre='Pantenol liquido (Provitamina B5)' WHERE producto_nombre='CREMA DE UREA' AND material_nombre='PANTENOL - LIQUIDO' AND material_id='MPPANTLI01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='CREMA DE UREA' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00078', material_nombre='Vitamina E líquida' WHERE producto_nombre='CREMA DE UREA' AND material_nombre='VITAMINA E - ACEITE' AND material_id='MPVITELI01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='EMULSION HIDRATANTE  B3+BHA' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00123', material_nombre='Trietanolamina' WHERE producto_nombre='EMULSION HIDRATANTE  B3+BHA' AND material_nombre='TRIETANOLAMINA 85%' AND material_id='MPTRIESO01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='BETAGLUCAN' AND material_id='MPBETASO02';
UPDATE formula_items SET material_id='MP00432', material_nombre='Pantenol liquido (Provitamina B5)' WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='PANTENOL LIQUIDO' AND material_id='MPPANTLI01';
UPDATE formula_items SET material_id='MP00436', material_nombre='QUIMCREAM (proveedor)' WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='QUIMCREAM' AND material_id='MPQUCRELI01';
UPDATE formula_items SET material_id='MP00437', material_nombre='Resveratrol' WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='RESVERATROL' AND material_id='MPRESVSO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00090', material_nombre='Triglicérido caprílico' WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='TRIGLICERIDO CAPRICO' AND material_id='MPTRICAL01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='ALFA ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='BETAGLUCAN' AND material_id='MPBETASO01';
UPDATE formula_items SET material_id='MP00418', material_nombre='Escualano' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='ESCUALENO' AND material_id='MPESCULI01';
UPDATE formula_items SET material_id='MP00262', material_nombre='N-acetil glucosamina' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='N-ACETILGLUCOSAMINA' AND material_id='MPGLUCSO01';
UPDATE formula_items SET material_id='MP00432', material_nombre='Pantenol liquido (Provitamina B5)' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='PANTENOL LIQUIDO' AND material_id='MPPANTLI01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00442', material_nombre='Sepiwhite MSH' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='UNDECILENOIL FENILALANINA' AND material_id='MPUPASO001';
UPDATE formula_items SET material_id='MP00078', material_nombre='Vitamina E líquida' WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='VITAMINA E ACEITE' AND material_id='MPVITAELI01';
UPDATE formula_items SET material_id='MP00402', material_nombre='Aceite de jojoba' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='ACEITE JOJOBA' AND material_id='MPACJOLI01';
UPDATE formula_items SET material_id='MP00212', material_nombre='Bautyterge AOS-40 / Asco AOS-40' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='AOS 40' AND material_id='MPAOSLI01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='BETAGLUCAN' AND material_id='MPBETASO02';
UPDATE formula_items SET material_id='MP00422', material_nombre='Fragancia fresa cremoso' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='FRAGANCIA FRESA CREMOSO' AND material_id='MPFRSALI01';
UPDATE formula_items SET material_id='MP00020', material_nombre='Yogurt cremoso' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='FRAGANCIA YOGURT CREMOSO' AND material_id='MPYOCRLI01';
UPDATE formula_items SET material_id='MP00073', material_nombre='Goma xanthan' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='GOMA XANTAN' AND material_id='MPGOXASO01';
UPDATE formula_items SET material_id='MP00070', material_nombre='Plantaren Lauryl 1200 / Eversoft 1200' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='LAURIL GLUCOSIDO' AND material_id='MPLAGLLI01';
UPDATE formula_items SET material_id='MP00128', material_nombre='BM-600' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='SILICONA BM 600' AND material_id='MPSILILI02';
UPDATE formula_items SET material_id='MP00090', material_nombre='Triglicérido caprílico' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='TRIGLICERIDO CAPRICO' AND material_id='MPTRICA01';
UPDATE formula_items SET material_id='MP00078', material_nombre='Vitamina E líquida' WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='VITAMINA E ACEITE' AND material_id='MPVITAELI01';
UPDATE formula_items SET material_id='MP00411', material_nombre='Asiaticosido (puro)' WHERE producto_nombre='ESENCIA DE CENTELLA ASIATICA' AND material_nombre='ASIATICOSIDO' AND material_id='MPASIASO01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='ESENCIA DE CENTELLA ASIATICA' AND material_nombre='BETAGLUCAN' AND material_id='MPBETASO03';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='ESENCIA DE CENTELLA ASIATICA' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00226', material_nombre='Ectoin' WHERE producto_nombre='ESENCIA DE CENTELLA ASIATICA' AND material_nombre='ECTOINA' AND material_id='MPECTOSO01';
UPDATE formula_items SET material_id='MP00441', material_nombre='Terpenos solubles 98%' WHERE producto_nombre='ESENCIA DE CENTELLA ASIATICA' AND material_nombre='TERPENOS SOLUBLE' AND material_id='MPTERPESO01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='GEL HIDRATANTE' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00432', material_nombre='Pantenol liquido (Provitamina B5)' WHERE producto_nombre='GEL HIDRATANTE' AND material_nombre='PANTENOL LIQUIDO' AND material_id='MPPANTLI01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='GEL HIDRATANTE' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00212', material_nombre='Bautyterge AOS-40 / Asco AOS-40' WHERE producto_nombre='LIMPIADOR FACIAL BHA 2%' AND material_nombre='AOS 40' AND material_id='MPALCESO01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='LIMPIADOR FACIAL BHA 2%' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEZ4USO01';
UPDATE formula_items SET material_id='MP00073', material_nombre='Goma xanthan' WHERE producto_nombre='LIMPIADOR FACIAL BHA 2%' AND material_nombre='GOMA XANTAN' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00123', material_nombre='Trietanolamina' WHERE producto_nombre='LIMPIADOR FACIAL BHA 2%' AND material_nombre='TRIETANOLAMINA 85%' AND material_id='MPTRIESO01';
UPDATE formula_items SET material_id='MP00212', material_nombre='Bautyterge AOS-40 / Asco AOS-40' WHERE producto_nombre='LIMPIADOR FACIAL HIDRATANTE' AND material_nombre='AOS 40' AND material_id='MPASCOLI01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='LIMPIADOR FACIAL HIDRATANTE' AND material_nombre='BETAGLUCAN' AND material_id='MPBETASO02';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='LIMPIADOR FACIAL HIDRATANTE' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00073', material_nombre='Goma xanthan' WHERE producto_nombre='LIMPIADOR FACIAL HIDRATANTE' AND material_nombre='GOMA XANTAN' AND material_id='MPGOXASO01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='LIMPIADOR FACIAL HIDRATANTE' AND material_nombre='PEPTIDOS DE COLAGENO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00212', material_nombre='Bautyterge AOS-40 / Asco AOS-40' WHERE producto_nombre='LIMPIADOR ILUMINADOR ACIDO KOJICO' AND material_nombre='AOS 40' AND material_id='MPASCOLI01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='LIMPIADOR ILUMINADOR ACIDO KOJICO' AND material_nombre='BETAGLUCAN' AND material_id='MPBETASO02';
UPDATE formula_items SET material_id='MP00073', material_nombre='Goma xanthan' WHERE producto_nombre='LIMPIADOR ILUMINADOR ACIDO KOJICO' AND material_nombre='GOMA XANTAN' AND material_id='MPGOXASO01';
UPDATE formula_items SET material_id='MP00105', material_nombre='Beauty Oil Rosa mosqueta' WHERE producto_nombre='MASCARILLA HIDRATANTE' AND material_nombre='ACEITE DE ROSA MOSQUETA' AND material_id='MPACROLI01';
UPDATE formula_items SET material_id='MP00418', material_nombre='Escualano' WHERE producto_nombre='MASCARILLA HIDRATANTE' AND material_nombre='ESCUALENO' AND material_id='MPESCULI01';
UPDATE formula_items SET material_id='MP00432', material_nombre='Pantenol liquido (Provitamina B5)' WHERE producto_nombre='MASCARILLA HIDRATANTE' AND material_nombre='PANTENOL LIQUIDO' AND material_id='MPPANTLI01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='MASCARILLA HIDRATANTE' AND material_nombre='PEPTIDOS DE COLAGENO POLVO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='MASCARILLA HIDRATANTE' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00400', material_nombre='1,2-Hexanediol' WHERE producto_nombre='MAXLASH' AND material_nombre='1,2-HEXANODIOL' AND material_id='MPHEXADSO01';
UPDATE formula_items SET material_id='MP00170', material_nombre='Acetyl tetrapeptide-3' WHERE producto_nombre='MAXLASH' AND material_nombre='ACETIL TETRAPEPTIDO-3' AND material_id='MPACTET3001';
UPDATE formula_items SET material_id='MP00403', material_nombre='Acetil tetrapeptido-40' WHERE producto_nombre='MAXLASH' AND material_nombre='ACETIL TETRAPEPTIDO-40' AND material_id='MPACETTE40';
UPDATE formula_items SET material_id='MP00147', material_nombre='L-arginina' WHERE producto_nombre='MAXLASH' AND material_nombre='ARGININA' AND material_id='MPARGISO01';
UPDATE formula_items SET material_id='MP00021', material_nombre='Fenoxietanol / Biosure' WHERE producto_nombre='MAXLASH' AND material_nombre='BIOSURE FE FENOXIETANOL' AND material_id='MPBIOFELI01';
UPDATE formula_items SET material_id='MP00193', material_nombre='Biotinoyl tripeptide-1' WHERE producto_nombre='MAXLASH' AND material_nombre='BIOTINOIL TRIPEPTIDO-1' AND material_id='MPBIOTSO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='MAXLASH' AND material_nombre='BIS-PEG-12 DIMETILSILOXANO' AND material_id='MPBISPEGSO01';
UPDATE formula_items SET material_id='MP00194', material_nombre='Copper tripeptide-1' WHERE producto_nombre='MAXLASH' AND material_nombre='COPPER TRIPEPTIDE-1 GHK-CU' AND material_id='MPGHKCUSO01';
UPDATE formula_items SET material_id='MP00419', material_nombre='Extracto trebol rojo' WHERE producto_nombre='MAXLASH' AND material_nombre='EXTRACTO TREBOL ROJO' AND material_id='MPTREBOLSO01';
UPDATE formula_items SET material_id='MP00425', material_nombre='L-Ergotioneina' WHERE producto_nombre='MAXLASH' AND material_nombre='L-ERGOTIONEINA' AND material_id='MPERGO01';
UPDATE formula_items SET material_id='MP00171', material_nombre='Myristoyl hexapeptide-16' WHERE producto_nombre='MAXLASH' AND material_nombre='MIRISTOIL HEXAPEPTIDO-16' AND material_id='MPMYRIH16';
UPDATE formula_items SET material_id='MP00187', material_nombre='Myristoyl pentapeptide-17' WHERE producto_nombre='MAXLASH' AND material_nombre='MIRISTOIL PENTAPEPTIDO-17' AND material_id='MPMYRIP17';
UPDATE formula_items SET material_id='MP00164', material_nombre='N-acetil cisteína' WHERE producto_nombre='MAXLASH' AND material_nombre='N-ACETIL-CISTEINA' AND material_id='MPNACISO01';
UPDATE formula_items SET material_id='MP00431', material_nombre='Palmitoil tripeptido-38' WHERE producto_nombre='MAXLASH' AND material_nombre='PALMITOIL TRIPEPTIDO-38' AND material_id='MPPALMTR38';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='MAXLASH' AND material_nombre='PEPTIDOS HIDROLIZADOS COLAGENO' AND material_id='MPCOLPEPSO01';
UPDATE formula_items SET material_id='MP00434', material_nombre='Peptidos hidrolizados queratina' WHERE producto_nombre='MAXLASH' AND material_nombre='PEPTIDOS HIDROLIZADOS QUERATINA' AND material_id='MPKERPEPSO01';
UPDATE formula_items SET material_id='MP00421', material_nombre='SAP' WHERE producto_nombre='MAXLASH' AND material_nombre='SODIUM ASCORBIL FOSFATO SAP' AND material_id='MPASCPHOSO01';
UPDATE formula_items SET material_id='MP00440', material_nombre='Vit E hidrosoluble' WHERE producto_nombre='MAXLASH' AND material_nombre='SODIUM TOCOFERIL FOSFATO' AND material_id='MPTOCOFE01';
UPDATE formula_items SET material_id='MP00160', material_nombre='Etil ascórbico acid' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='3-O ACIDO ETIL ASCORBICO' AND material_id='MPACIETASO01';
UPDATE formula_items SET material_id='MP00409', material_nombre='THD ascorbato' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='ASCORBATO DE TETRAHEXILDECILO' AND material_id='MPTEISASO01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00418', material_nombre='Escualano' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='ESCUALENO' AND material_id='MPESCULI01';
UPDATE formula_items SET material_id='MP00421', material_nombre='SAP' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='FOSFATO DE ASCORBILO SODICO' AND material_id='MPFOASSO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='GRANSIL VX419' AND material_id='MPGRANLI01';
UPDATE formula_items SET material_id='MP00090', material_nombre='Triglicérido caprílico' WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='TRIGLICERIDO CAPRICO' AND material_id='MPTRICAL01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='SUERO ANTIOXIDANTE VITAMINA C+B3' AND material_nombre='ALFA ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00410', material_nombre='Ascorbil glucosido' WHERE producto_nombre='SUERO ANTIOXIDANTE VITAMINA C+B3' AND material_nombre='ASCORBIC GLUCOSIDE' AND material_id='MPASGLSO01';
UPDATE formula_items SET material_id='MP00262', material_nombre='N-acetil glucosamina' WHERE producto_nombre='SUERO ANTIOXIDANTE VITAMINA C+B3' AND material_nombre='GLUCOSAMINA NAG' AND material_id='MPGLUCSO01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='SUERO ANTIOXIDANTE VITAMINA C+B3' AND material_nombre='PEPTIDOS DE COLAGENO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00439', material_nombre='Silicona liquida' WHERE producto_nombre='SUERO ANTIOXIDANTE VITAMINA C+B3' AND material_nombre='SILICONA LIQUIDA' AND material_id='MPSILILI01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='SUERO AZ + B3' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00400', material_nombre='1,2-Hexanediol' WHERE producto_nombre='SUERO DE NIACINAMIDA 5% FORMULA NUEVA' AND material_nombre='1,2 HEXANEDIOL' AND material_id='MPHEXDILI01';
UPDATE formula_items SET material_id='MP00411', material_nombre='Asiaticosido (puro)' WHERE producto_nombre='SUERO DE NIACINAMIDA 5% FORMULA NUEVA' AND material_nombre='ASIATICOSIDO' AND material_id='MPASIASO01';
UPDATE formula_items SET material_id='MP00226', material_nombre='Ectoin' WHERE producto_nombre='SUERO DE NIACINAMIDA 5% FORMULA NUEVA' AND material_nombre='ECTOINA' AND material_id='MPECTOSO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='SUERO DE NIACINAMIDA 5% FORMULA NUEVA' AND material_nombre='GRANSIL VX419' AND material_id='MPGRANLI01';
UPDATE formula_items SET material_id='MP00441', material_nombre='Terpenos solubles 98%' WHERE producto_nombre='SUERO DE NIACINAMIDA 5% FORMULA NUEVA' AND material_nombre='TERPENOS SOLUBLES 98%' AND material_id='MPTERSSO01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='SUERO DE RETINALDEHIDO 0.05%' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00443', material_nombre='Acido ferulico' WHERE producto_nombre='SUERO DE RETINALDEHIDO 0.05%' AND material_nombre='ÁCIDO FERÚLICO' AND material_id='MPACFESO01';
UPDATE formula_items SET material_id='MP00160', material_nombre='Etil ascórbico acid' WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='3-O ACIDO ETIL ASCORBICO' AND material_id='MPACIETASO01';
UPDATE formula_items SET material_id='MP00230', material_nombre='Vitamina C' WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='ACIDO ASCORBICO' AND material_id='MPACASSO01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='ALFA ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00413', material_nombre='Beta-ciclodextrina' WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='BETA-CICLODEXTRINA' AND material_id='MPCICLOS01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='GRANSIL VX419' AND material_id='MPGRANLI01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='PEPTIDOS DE COLAGENO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='SUERO EXFOLIANTE NOVA PHA' AND material_nombre='ALFA  ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00413', material_nombre='Beta-ciclodextrina' WHERE producto_nombre='SUERO EXFOLIANTE NOVA PHA' AND material_nombre='BETA-CICLODEXTRINA' AND material_id='MPCICLOS01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='SUERO EXFOLIANTE NOVA PHA' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='SUERO EXFOLIANTE NOVA PHA' AND material_nombre='GRANSIL VX 419' AND material_id='MPGRANLI01';
UPDATE formula_items SET material_id='MP00423', material_nombre='Soda caustica' WHERE producto_nombre='SUERO EXFOLIANTE NOVA PHA' AND material_nombre='HIDROXIDO DE SODIO (SOLUCION 50%)' AND material_id='MPHIDSOLI01';
UPDATE formula_items SET material_id='MP00214', material_nombre='Betaglucano' WHERE producto_nombre='SUERO HIDRATANTE AH 1.5%' AND material_nombre='BETAGLUCAM' AND material_id='MPBETASO02';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='SUERO ILUMINADOR AHA+AH.' AND material_nombre='ALFA ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00262', material_nombre='N-acetil glucosamina' WHERE producto_nombre='SUERO ILUMINADOR AHA+AH.' AND material_nombre='GLUCOSAMINA NAG' AND material_id='MPGLUCSO01';
UPDATE formula_items SET material_id='MP00441', material_nombre='Terpenos solubles 98%' WHERE producto_nombre='SUERO ILUMINADOR AHA+AH.' AND material_nombre='TERPENOS SOLUBLES' AND material_id='MPTERSOL01';
UPDATE formula_items SET material_id='MP00400', material_nombre='1,2-Hexanediol' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='1,2 HEXANEDIOL' AND material_id='MPHEXDILI01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='ALFA ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='ALFA ARBUTINA' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00413', material_nombre='Beta-ciclodextrina' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='BETA-CICLODEXTRINA' AND material_id='MPCICLOS01';
UPDATE formula_items SET material_id='MP00181', material_nombre='Centella asiatica extract' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='CENTELLA ASIATICA POLVO' AND material_id='MPEXGOSO01';
UPDATE formula_items SET material_id='MP00420', material_nombre='Fitato de sodio' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='FITATO DE SODIO' AND material_id='MPFISOSO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='GRANSIL VX419' AND material_id='MPACSASO01';
UPDATE formula_items SET material_id='MP00262', material_nombre='N-acetil glucosamina' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='N-ACETILGLUCOSAMINA' AND material_id='MPGLUCSO01';
UPDATE formula_items SET material_id='MP00429', material_nombre='Oligopeptido-68' WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='OLIGOPEPTIDO 68' AND material_id='MPOLIPESO01';
UPDATE formula_items SET material_id='MP00192', material_nombre='Acetyl hexapeptide-8' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='ACETYL HEXAPEPTIDE 8' AND material_id='MPACHESO01';
UPDATE formula_items SET material_id='MP00175', material_nombre='Acetyl tetrapeptide-5' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='ACETYL TETRAPEPTIDE 5' AND material_id='MPACTESO01';
UPDATE formula_items SET material_id='MP00405', material_nombre='AH 1500 kDa' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='ACIDO HIALURONICO 1500KD' AND material_id='MPACHISO03';
UPDATE formula_items SET material_id='MP00406', material_nombre='AH 300 kDa' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='ACIDO HIALURONICO 300KD' AND material_id='MPACHISO02';
UPDATE formula_items SET material_id='MP00163', material_nombre='Ácido hialurónico 50 kD' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='ACIDO HIALURONICO 50KD' AND material_id='MPACHISO01';
UPDATE formula_items SET material_id='MP00194', material_nombre='Copper tripeptide-1' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='COPPER TRIPEPTIDE 1' AND material_id='MPCOTRSO01';
UPDATE formula_items SET material_id='MP00417', material_nombre='Syn-Ake' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='DIPÉPTIDO DIAMINOBUTIROIL BENZALAMIDA DIACETATO' AND material_id='MPDIBEDISO01';
UPDATE formula_items SET material_id='MP00262', material_nombre='N-acetil glucosamina' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='GLUCOSAMINA (NAG)' AND material_id='MPGLUCSO01';
UPDATE formula_items SET material_id='MP00072', material_nombre='Gransil VX-419' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='GRANSIL VX 419' AND material_id='MPGRANLI01';
UPDATE formula_items SET material_id='MP00228', material_nombre='Palmitoyl pentapeptide-4' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='PALMITOYL PENTAPEPTIDE 4' AND material_id='MPPAPESO01';
UPDATE formula_items SET material_id='MP00172', material_nombre='Palmitoyl tetrapeptide-7' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='PALMITOYL TETRAPEPTIDE 7' AND material_id='MPPALTESO01';
UPDATE formula_items SET material_id='MP00190', material_nombre='Palmitoyl tripeptide-1' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='PALMITOYL TRIPEPTIDE 1' AND material_id='MPPALTRISO02';
UPDATE formula_items SET material_id='MP00191', material_nombre='Palmitoyl tripeptide-5' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='PALMITOYL TRIPEPTIDE 5' AND material_id='MPPALTRISO01';
UPDATE formula_items SET material_id='MP00223', material_nombre='ADN vegetal (PDRN)' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='PDRN (SODIUM DNA)' AND material_id='MPPOBOSO01';
UPDATE formula_items SET material_id='MP00285', material_nombre='Péptido de colágeno' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='PEPTIDOS DE COLAGENO POLVO' AND material_id='MPPECOSO01';
UPDATE formula_items SET material_id='MP00123', material_nombre='Trietanolamina' WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='TRIETANOLAMINA 85%' AND material_id='MPTRIELO01';
UPDATE formula_items SET material_id='MP00400', material_nombre='1,2-Hexanediol' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='1,2-HEXANODIOL' AND material_id='MPHEXADSO01';
UPDATE formula_items SET material_id='MP00403', material_nombre='Acetil tetrapeptido-40' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='ACETIL TETRAPEPTIDO-40' AND material_id='MPACETTE40';
UPDATE formula_items SET material_id='MP00404', material_nombre='LHA' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='ACIDO CAPRILOIL SALICILICO LHA' AND material_id='MPACCASAS01';
UPDATE formula_items SET material_id='MP00234', material_nombre='Apigenin' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='APIGENINA' AND material_id='MPAPIGESO01';
UPDATE formula_items SET material_id='MP00413', material_nombre='Beta-ciclodextrina' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='BETA-CICLODEXTRINA' AND material_id='MPCICLOS01';
UPDATE formula_items SET material_id='MP00021', material_nombre='Fenoxietanol / Biosure' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='BIOSURE FE FENOXIETANOL' AND material_id='MPBIOFELI01';
UPDATE formula_items SET material_id='MP00008', material_nombre='Carbopol' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='CARBOPOL ULTREZ-21' AND material_id='MPCARBSO01';
UPDATE formula_items SET material_id='MP00414', material_nombre='Ceramida NP' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='CERAMIDA NP' AND material_id='MPCERASO01';
UPDATE formula_items SET material_id='MP00415', material_nombre='CTM (Sepiwhite MSH)' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='CETIL TRANEXAMATO MESILATO CTM' AND material_id='MPCTMESO01';
UPDATE formula_items SET material_id='MP00242', material_nombre='Extracto CO2 de romero' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='CO2 SUPERCRITICO ROMERO' AND material_id='MPCO2ROSO01';
UPDATE formula_items SET material_id='MP00416', material_nombre='Cetiol CC' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='DICAPRILIL CARBONATO' AND material_id='MPDICASO01';
UPDATE formula_items SET material_id='MP00226', material_nombre='Ectoin' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='ECTOINA' AND material_id='MPECTOSO01';
UPDATE formula_items SET material_id='MP00420', material_nombre='Fitato de sodio' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='FITATO DE SODIO' AND material_id='MPNAFIESO01';
UPDATE formula_items SET material_id='MP00424', material_nombre='HPR / Granactive Retinoid' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='HIDROXIPINOCOLONA RETINOATO HPR' AND material_id='MPHPRSO01';
UPDATE formula_items SET material_id='MP00250', material_nombre='Myristoyl nonapeptide-3' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='MIRISTOIL NONAPEPTIDO-3' AND material_id='MPMYRINAN3';
UPDATE formula_items SET material_id='MP00427', material_nombre='NAD+' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='NAD+' AND material_id='MPNADPLUSO01';
UPDATE formula_items SET material_id='MP00428', material_nombre='Nitruro de boro' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='NITRURO DE BORO' AND material_id='MPBORNISO01';
UPDATE formula_items SET material_id='MP00275', material_nombre='NMN' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='NMN MONONUCLEOTIDO NICOTINAMIDA' AND material_id='MPNMNSO01';
UPDATE formula_items SET material_id='MP00429', material_nombre='Oligopeptido-68' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='OLIGOPEPTIDO-68' AND material_id='MPOLIGO68';
UPDATE formula_items SET material_id='MP00172', material_nombre='Palmitoyl tetrapeptide-7' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='PALMITOIL TETRAPEPTIDO-7' AND material_id='MPPALMT7';
UPDATE formula_items SET material_id='MP00190', material_nombre='Palmitoyl tripeptide-1' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='PALMITOIL TRIPEPTIDO-1' AND material_id='MPPALMTR01';
UPDATE formula_items SET material_id='MP00431', material_nombre='Palmitoil tripeptido-38' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='PALMITOIL TRIPEPTIDO-38' AND material_id='MPPALMTR38';
UPDATE formula_items SET material_id='MP00433', material_nombre='PEG-12 dimeticona' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='PEG-12 DIMETILSILOXANO' AND material_id='MPPEGDISO01';
UPDATE formula_items SET material_id='MP00435', material_nombre='Propanediol PDO' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='PROPANEDIOL PDO' AND material_id='MPPROPD001';
UPDATE formula_items SET material_id='MP00111', material_nombre='Puresil ORG01' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='PURESIL ORG 01' AND material_id='MPPURSISO01';
UPDATE formula_items SET material_id='MP00261', material_nombre='Retinaldehído' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='RETINAL' AND material_id='MPRETINSO01';
UPDATE formula_items SET material_id='MP00438', material_nombre='Retinil retinoato (RR)' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='RETINIL RETINOATO RR' AND material_id='MPRETYRE01';
UPDATE formula_items SET material_id='MP00289', material_nombre='Silica MSS-500/3H' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='SILICA MSS-500' AND material_id='MPSILICSO01';
UPDATE formula_items SET material_id='MP00223', material_nombre='ADN vegetal (PDRN)' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='SODIUM DNA PDRN' AND material_id='MPPDRNS001';
UPDATE formula_items SET material_id='MP00417', material_nombre='Syn-Ake' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='SYN-AKE' AND material_id='MPSYNAKESO01';
UPDATE formula_items SET material_id='MP00409', material_nombre='THD ascorbato' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='TETRAHEXILDECIL ASCORBATO THD' AND material_id='MPTHDASO01';
UPDATE formula_items SET material_id='MP00123', material_nombre='Trietanolamina' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='TRIETANOLAMINA 85%' AND material_id='MPTRIELO01';
UPDATE formula_items SET material_id='MP00078', material_nombre='Vitamina E líquida' WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='VITAMINA E TOCOFEROL' AND material_id='MPVITAELI01';
UPDATE formula_items SET material_id='MP00183', material_nombre='Alpha arbutina' WHERE producto_nombre='Suero Exfoliante BHA 2%' AND material_nombre='ALFA ARBUTINA  (LYPHAR)' AND material_id='MPALARSO01';
UPDATE formula_items SET material_id='MP00073', material_nombre='Goma xanthan' WHERE producto_nombre='Suero Exfoliante BHA 2%' AND material_nombre='GOMA XANTAN' AND material_id='MPGOXASO01';
UPDATE formula_items SET material_id='MP00426', material_nombre='MSM' WHERE producto_nombre='Suero Exfoliante BHA 2%' AND material_nombre='METILSULFONILMETANO' AND material_id='MPMETISO01';
UPDATE formula_items SET material_id='MP00408', material_nombre='Alcohol cetilico' WHERE producto_nombre='Suero RETINAL +' AND material_nombre='ALCOHOL CETITLICO' AND material_id='MPALCESO01';
UPDATE formula_items SET material_id='MP00173', material_nombre='Bakuchiol' WHERE producto_nombre='Suero RETINAL +' AND material_nombre='BACKUCHIOL' AND material_id='MPBAKULI01';
UPDATE formula_items SET material_id='MP00437', material_nombre='Resveratrol' WHERE producto_nombre='Suero RETINAL +' AND material_nombre='RESVERATROL' AND material_id='MPRESVSO01';

-- 6) DELETEs formula_items (aguas internas)
DELETE FROM formula_items WHERE producto_nombre='AZ HIBRID CLEAR' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='CONTORNO DE CAFEINA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='CONTORNO DE OJOS MULTIPEPTIDOS' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='CONTORNO DE OJOS RETINALDEHIDO 0.05%' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUAS01';
DELETE FROM formula_items WHERE producto_nombre='CREMA CORPORAL RENOVA BODY' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='CREMA DE UREA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='EMULSION HIDRATANTE  B3+BHA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='EMULSION HIDRATANTE ANTIOXIDANTE' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='EMULSION HIDRATANTE ILUMINADORA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='EMULSION LIMPIADORA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='ESENCIA DE CENTELLA ASIATICA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI02';
DELETE FROM formula_items WHERE producto_nombre='ESENCIA ILUMINADORA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='GEL HIDRATANTE' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='LIMPIADOR FACIAL BHA 2%' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='LIMPIADOR FACIAL HIDRATANTE' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI02';
DELETE FROM formula_items WHERE producto_nombre='LIMPIADOR ILUMINADOR ACIDO KOJICO' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='MASCARILLA HIDRATANTE' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='MAXLASH' AND material_nombre='AGUA PURIFICADA TOTAL' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO ANTIOXIDANTE RENOVA C10' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO ANTIOXIDANTE VITAMINA C+B3' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO AZ + B3' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUAL01';
DELETE FROM formula_items WHERE producto_nombre='SUERO DE NIACINAMIDA 5% FORMULA NUEVA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO DE RETINALDEHIDO 0.05%' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO DE VITAMINA C+ FORMULA NUEVA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO EXFOLIANTE NOVA PHA' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO HIDRATANTE AH 1.5%' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUAL01';
DELETE FROM formula_items WHERE producto_nombre='SUERO ILUMINADOR AHA+AH.' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI02';
DELETE FROM formula_items WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO ILUMINADOR TRX' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO MULTIPEPTIDOS' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='SUERO TRIACTIVE RETINOID NAD+' AND material_nombre='AGUA PURIFICADA (total fases)' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='Suero Exfoliante BHA 2%' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';
DELETE FROM formula_items WHERE producto_nombre='Suero RETINAL +' AND material_nombre='AGUA DESIONIZADA' AND material_id='MPAGUALI01';

COMMIT;

-- ROLLBACK si algo sale mal:
-- DELETE FROM formula_items;
-- INSERT INTO formula_items SELECT * FROM formula_items_backup_20260428;
-- DELETE FROM maestro_mps;
-- INSERT INTO maestro_mps SELECT * FROM maestro_mps_backup_20260428;
