MODULOS_HTML = (
    "<!DOCTYPE html>\n"
    "<html lang=\"es\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>Cortex Labs · Módulos</title>\n"
    "<link rel=\"stylesheet\" href=\"/static/cortex.css?v=cortex3\">\n"
    "<script>(function(){try{var t=localStorage.getItem(\"cx-theme\");if(t===\"dark\")document.documentElement.setAttribute(\"data-theme\",\"dark\");}catch(e){}})();</script>\n"
    "<link rel=\"manifest\" href=\"/manifest.json\">\n"
    "<meta name=\"theme-color\" content=\"#6d28d9\">\n"
    "<meta name=\"application-name\" content=\"Cortex Labs\">\n"
    "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"
    "<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n"
    "<meta name=\"apple-mobile-web-app-title\" content=\"Cortex Labs\">\n"
    "<meta name=\"mobile-web-app-capable\" content=\"yes\">\n"
    "<meta name=\"description\" content=\"Cortex Labs · El cerebro operativo de tu laboratorio · Desarrollado por HHA Group\">\n"
    "<meta name=\"author\" content=\"HHA Group\">\n"
    "<link rel=\"icon\" type=\"image/x-icon\" href=\"/static/favicon.ico?v=cortex3\">\n"
    "<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/static/icons/favicon-32.png?v=cortex3\">\n"
    "<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/static/icons/apple-touch-icon-180.png?v=cortex3\">\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0;}\n"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f5f4f0;color:#1c1917;min-height:100vh;}\n"
    ".header{background:#fff;border-bottom:1px solid #e7e5e4;padding:18px 28px;display:flex;align-items:center;justify-content:space-between;}\n"
    ".header-logo{font-size:18px;font-weight:800;color:#0f3a1f;}\n"
    ".header-sub{font-size:11px;color:#78716c;margin-top:2px;}\n"
    ".header-user{font-size:12px;color:#78716c;}\n"
    ".header-user strong{color:#1c1917;}\n"
    ".main{padding:32px 24px;max-width:1100px;margin:0 auto;}\n"
    ".page-title{font-size:22px;font-weight:800;color:#0f3a1f;margin-bottom:4px;}\n"
    ".page-sub{font-size:13px;color:#78716c;margin-bottom:32px;}\n"
    ".section{margin-bottom:36px;}\n"
    ".section-label{font-size:11px;font-weight:800;color:#57534e;text-transform:uppercase;letter-spacing:1.2px;margin-bottom:14px;padding-bottom:8px;border-bottom:2px solid #e7e5e4;display:flex;align-items:center;justify-content:space-between;}\n"
    ".section-label .hint{font-size:10px;color:#a8a29e;font-weight:500;text-transform:none;letter-spacing:0;}\n"
    ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:14px;}\n"
    ".mod-card{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;padding:22px 12px 18px;background:#fff;border:1px solid #e7e5e4;border-radius:12px;text-decoration:none;color:#1c1917;transition:.15s;min-height:110px;}\n"
    ".mod-card:hover{background:#fafaf9;border-color:#a8a29e;transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,0.06);}\n"
    ".mod-card.featured{background:linear-gradient(135deg,#fef3c7 0%,#fde68a 100%);border-color:#f59e0b;}\n"
    ".mod-card.featured:hover{background:linear-gradient(135deg,#fde68a 0%,#fcd34d 100%);}\n"
    ".mod-icon{font-size:30px;line-height:1;color:#6d28d9;display:inline-flex;align-items:center;justify-content:center;}\n"".mod-icon .cx-ico{width:34px;height:34px;}\n"
    ".mod-name{font-size:13px;font-weight:700;text-align:center;}\n"
    ".mod-sub{font-size:10px;color:#78716c;text-align:center;font-weight:500;line-height:1.3;}\n"
    ".footer{margin-top:40px;text-align:center;}\n"
    ".logout-btn{display:inline-flex;align-items:center;gap:6px;padding:8px 22px;background:transparent;border:1px solid #d6d3d1;border-radius:8px;color:#78716c;text-decoration:none;font-size:12px;font-weight:600;}\n"
    ".logout-btn:hover{border-color:#7f1d1d;color:#dc2626;}\n"
    "@media (max-width:768px){\n"
    "  .header{padding:14px 16px;flex-wrap:wrap;gap:8px;}\n"
    "  .header-logo{font-size:16px;}\n"
    "  .main{padding:20px 14px;}\n"
    "  .page-title{font-size:18px;}\n"
    "  .grid{grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:10px;}\n"
    "  .mod-card{padding:16px 8px 14px;min-height:90px;}\n"
    "  .mod-icon .cx-ico{width:26px;height:26px;}\n"
    "  .mod-name{font-size:12px;}\n"
    "}\n"
    "@media (max-width:480px){\n"
    "  .grid{grid-template-columns:repeat(3,1fr);}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"header\">\n"
    "  <div style=\"display:flex;align-items:center;gap:14px;\">\n"
    "    <img src=\"/static/icons/icon-192.png?v=cortex3\" alt=\"Cortex Labs\" "
    "style=\"width:48px;height:48px;border-radius:11px;box-shadow:0 4px 12px rgba(109,40,217,0.25);flex-shrink:0;\">\n"
    "    <div>\n"
    "      <div class=\"header-logo\" style=\"display:flex;align-items:baseline;gap:8px;\">"
    "<span style=\"background:linear-gradient(135deg,#a78bfa,#6d28d9);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;\">Cortex Labs</span>"
    "<span style=\"font-size:9px;color:#a78bfa;font-weight:700;letter-spacing:1px;text-transform:uppercase;border:1px solid #c4b5fd;padding:1px 5px;border-radius:3px;\">v1.0</span>"
    "</div>\n"
    "      <div class=\"header-sub\">by <strong style=\"color:#1c1917\">HHA Group</strong> &middot; Espagiria &middot; ANIMUS Lab</div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div style=\"display:flex;align-items:center;gap:14px;\">\n"
    "    <button id=\"campana-btn\" onclick=\"abrirCentroNotif()\" title=\"Notificaciones\" "
    "style=\"position:relative;background:transparent;border:1px solid #d6d3d1;color:#1c1917;"
    "border-radius:8px;width:38px;height:38px;cursor:pointer;font-size:18px;\">"
    "&#128276;<span id=\"campana-badge\" style=\"display:none;position:absolute;top:-4px;right:-4px;"
    "background:#dc2626;color:#fff;border-radius:10px;padding:1px 6px;font-size:10px;font-weight:700;\">0</span>"
    "</button>\n"
    "    <div class=\"header-user\">Usuario: <strong>{usuario}</strong></div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"main\">\n"
    "  <div class=\"page-sub\" style=\"margin-top:8px;margin-bottom:28px;\">Hola <strong style=\"color:#1c1917\">{usuario}</strong> &middot; Selecciona un módulo. Solo ingresarás a los que tienes autorización.</div>\n"
    "\n"
    "  <!-- VISTA EJECUTIVA (admins) -->\n"
    "  <div class=\"section\" id=\"sec-ceo\" style=\"display:none;\">\n"
    "    <div class=\"section-label\">&#x1F3AF; CEO &middot; Vista del día <span class=\"hint\">tu vista única</span></div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card featured\" href=\"/hoy\">"
    "<span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2M12 20v2M4 12H2M22 12h-2M5.6 5.6 4.2 4.2M19.8 19.8l-1.4-1.4M5.6 18.4l-1.4 1.4M19.8 4.2l-1.4 1.4\"/></svg></span>"
    "<span class=\"mod-name\" style=\"color:#92400e\">HOY</span>"
    "<span class=\"mod-sub\" style=\"color:#92400e\">qué pasa en toda la empresa</span></a>\n"
    "      <a class=\"mod-card\" href=\"/gerencia\">"
    "<span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M3 9l9-6 9 6\"/><path d=\"M5 21V11M19 21V11M9 21v-8M15 21v-8M2 21h20\"/></svg></span>"
    "<span class=\"mod-name\">Gerencia</span>"
    "<span class=\"mod-sub\">metas YTD &middot; estrategia</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "  <script>\n"
    "    if({usuario_es_admin}){{ document.getElementById('sec-ceo').style.display=''; }}\n"
    "  </script>\n"
    "\n"
    "  <!-- OPERACIONES -->\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F3ED; Operaciones <span class=\"hint\">día a día productivo y comercial</span></div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/inventarios\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M21 7.5l-9-5-9 5 9 5z\"/><path d=\"M3 7.5v9l9 5 9-5v-9M12 12.5v9\"/></svg></span><span class=\"mod-name\">Planta</span><span class=\"mod-sub\">stock &middot; lotes &middot; recepción</span></a>\n"
    "      <a class=\"mod-card\" href=\"/calidad\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M9 3h6M10 3v6.5L4 19a2 2 0 001.7 3h12.6a2 2 0 001.7-3l-6-9.5V3\"/><path d=\"M6 14h12\"/></svg></span><span class=\"mod-name\">Calidad</span><span class=\"mod-sub\">cuarentena &middot; NCs</span></a>\n"
    "      <a class=\"mod-card\" href=\"/tecnica\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M14.7 6.3a4 4 0 005.7-5.7L18 3l-2-1-1-2-2.6 2.6a4 4 0 005.3 5.4z\"/><path d=\"M14 9 4 19l3 3 10-10\"/></svg></span><span class=\"mod-name\">Dirección Técnica</span><span class=\"mod-sub\">fórmulas &middot; INVIMA &middot; SOPs</span></a>\n"
    "      <a class=\"mod-card\" href=\"/compras\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><circle cx=\"9\" cy=\"21\" r=\"1\"/><circle cx=\"20\" cy=\"21\" r=\"1\"/><path d=\"M2 3h2l3 13h12l3-9H6\"/></svg></span><span class=\"mod-name\">Compras</span><span class=\"mod-sub\">OCs &middot; proveedores</span></a>\n"
    "      <a class=\"mod-card\" href=\"/solicitudes\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z\"/><path d=\"M14 2v6h6M9 13h6M9 17h6M9 9h2\"/></svg></span><span class=\"mod-name\">Solicitudes</span><span class=\"mod-sub\">pedidos compra</span></a>\n"
    "      <a class=\"mod-card\" href=\"/clientes\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/><path d=\"M22 21v-2a4 4 0 00-3-3.9M16 3.1a4 4 0 010 7.8\"/></svg></span><span class=\"mod-name\">Clientes</span><span class=\"mod-sub\">B2B &middot; pedidos &middot; despachos</span></a>\n"
    "      <a class=\"mod-card\" href=\"/marketing\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M3 11v3a1 1 0 001 1h2.5l8 5V5l-8 5H4a1 1 0 00-1 1z\"/><path d=\"M19 12a4 4 0 000-5.7\"/></svg></span><span class=\"mod-name\">Marketing</span><span class=\"mod-sub\">campañas &middot; influencers</span></a>\n"
    "      <a class=\"mod-card\" href=\"/animus\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M12 3l1.9 5.4L19 10l-5.1 1.6L12 17l-1.9-5.4L5 10l5.1-1.6L12 3z\"/><path d=\"M19 17l.6 1.7L21 19l-1.4.3L19 21l-.6-1.7L17 19l1.4-.3z\"/></svg></span><span class=\"mod-name\">ÁNIMUS Lab</span><span class=\"mod-sub\">marca DTC &middot; Shopify</span></a>\n"
    "      <a class=\"mod-card\" href=\"/espagiria\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M12 21V8M12 8c-3 0-6-2-6-5 3 0 6 2 6 5z\"/><path d=\"M12 8c3 0 6-2 6-5-3 0-6 2-6 5zM8 14c-2 0-4-1-4-3 2 0 4 1 4 3zM16 14c2 0 4-1 4-3-2 0-4 1-4 3z\"/></svg></span><span class=\"mod-name\">Espagiria</span><span class=\"mod-sub\">panel asistente</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- TESORERIA + PERSONAS -->\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F4B0; Tesorería &amp; Personas <span class=\"hint\">administrativo</span></div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/tesoreria\" style=\"background:linear-gradient(135deg,#dcfce7 0%,#bbf7d0 100%);border-color:#15803d;\"><span class=\"mod-icon\" style=\"color:#15803d\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><rect x=\"2\" y=\"6\" width=\"20\" height=\"12\" rx=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M6 12h.01M18 12h.01\"/></svg></span><span class=\"mod-name\" style=\"color:#15803d\">Tesorería</span><span class=\"mod-sub\" style=\"color:#15803d\">caja &middot; P&amp;L &middot; facturas &middot; SIIGO</span></a>\n"
    "      <a class=\"mod-card\" href=\"/rrhh\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/><path d=\"M23 21v-2a4 4 0 00-3-3.9M16 3.1a4 4 0 010 7.8\"/></svg></span><span class=\"mod-name\">RRHH</span><span class=\"mod-sub\">empleados &middot; nómina &middot; SGSST</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <!-- COORDINACION -->\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F4AC; Coordinación <span class=\"hint\">comunicación interna</span></div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/comunicacion\"><span class=\"mod-icon\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"cx-ico\"><path d=\"M9 12l2 2 4-4\"/><circle cx=\"12\" cy=\"12\" r=\"9\"/></svg></span><span class=\"mod-name\">Compromisos &amp; Chat</span><span class=\"mod-sub\">tareas RACI &middot; actas</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"footer\">\n"
    "    <a class=\"logout-btn\" href=\"/logout\">&#x23CF;&#xFE0F; Cerrar sesión</a>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<footer style=\"padding:24px 20px;border-top:1px solid #e7e5e4;margin-top:20px;text-align:center;font-size:11px;color:#a8a29e;background:#fafaf9;\">\n"
    "  <div style=\"display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;\">\n"
    "    <span style=\"font-weight:700;color:#6d28d9;letter-spacing:0.3px;font-size:13px;\">Cortex Labs</span>\n"
    "    <span style=\"font-size:10px;color:#a78bfa;font-weight:600;letter-spacing:1px;text-transform:uppercase;border:1px solid #c4b5fd;padding:1px 6px;border-radius:3px;\">v1.0</span>\n"
    "  </div>\n"
    "  <div style=\"margin-top:6px;font-style:italic;color:#78716c;\">El cerebro operativo de tu laboratorio</div>\n"
    "  <div style=\"margin-top:10px;letter-spacing:1px;text-transform:uppercase;font-size:10px;\">Desarrollado por <strong style=\"color:#1c1917\">HHA Group</strong></div>\n"
    "  <div style=\"margin-top:6px;color:#d6d3d1;font-size:10px;\">&copy; 2026 HHA Group S.A.S. &middot; Todos los derechos reservados</div>\n"
    "</footer>\n"
    "\n"
    "<!-- Modal: Centro de Notificaciones -->\n"
    "<div id=\"modal-notif\" style=\"display:none;position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:9999;align-items:flex-start;justify-content:center;padding:80px 16px 16px;\" onclick=\"if(event.target===this)cerrarCentroNotif()\">\n"
    "  <div style=\"background:#fff;border:1px solid #e7e5e4;border-radius:12px;width:680px;max-width:96vw;max-height:80vh;overflow-y:auto;color:#1c1917;\">\n"
    "    <div style=\"padding:18px 22px;border-bottom:1px solid #e7e5e4;display:flex;align-items:center;justify-content:space-between;\">\n"
    "      <div>\n"
    "        <h2 style=\"margin:0;font-size:1.15em;\">&#128276; Notificaciones</h2>\n"
    "        <div id=\"notif-stats\" style=\"font-size:11px;color:#78716c;margin-top:3px;\"></div>\n"
    "      </div>\n"
    "      <button onclick=\"cerrarCentroNotif()\" style=\"background:transparent;border:1px solid #d6d3d1;color:#1c1917;border-radius:6px;width:32px;height:32px;cursor:pointer;font-size:18px;\">&times;</button>\n"
    "    </div>\n"
    "    <div id=\"notif-body\" style=\"padding:18px 22px;\"><div style=\"text-align:center;color:#a8a29e;padding:40px;\">Cargando...</div></div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "function fmtCount(n){return n>9?'9+':String(n);}\n"
    "async function refreshCampana(){\n"
    "  try{\n"
    "    var r = await fetch('/api/notificaciones/count');\n"
    "    var d = await r.json();\n"
    "    var b = document.getElementById('campana-badge');\n"
    "    var btn = document.getElementById('campana-btn');\n"
    "    if(!b||!btn) return;\n"
    "    if(d.count > 0){\n"
    "      b.style.display = 'inline-block';\n"
    "      b.textContent = fmtCount(d.count);\n"
    "      btn.style.borderColor = '#dc2626';\n"
    "    } else {\n"
    "      b.style.display = 'none';\n"
    "      btn.style.borderColor = '#d6d3d1';\n"
    "    }\n"
    "  } catch(e){}\n"
    "}\n"
    "function abrirCentroNotif(){\n"
    "  var m = document.getElementById('modal-notif');\n"
    "  m.style.display = 'flex';\n"
    "  cargarNotifs();\n"
    "}\n"
    "function cerrarCentroNotif(){ document.getElementById('modal-notif').style.display = 'none'; refreshCampana(); }\n"
    "function _esc(s){return String(s||'').replace(/[<>&\"]/g, c=>({'<':'&lt;','>':'&gt;','&':'&amp;','\\\"':'&quot;'}[c]));}\n"
    "async function cargarNotifs(){\n"
    "  var body = document.getElementById('notif-body');\n"
    "  var stats = document.getElementById('notif-stats');\n"
    "  try{\n"
    "    var r = await fetch('/api/notificaciones/centro');\n"
    "    var d = await r.json();\n"
    "    if(!r.ok){ body.innerHTML='<div style=\"color:#dc2626;\">'+_esc(d.error||'')+'</div>'; return; }\n"
    "    var ps = d.por_severidad;\n"
    "    stats.innerHTML = '&#128308; '+ps.alta+' alta &middot; &#128993; '+ps.media+' media &middot; &#128309; '+ps.info+' info';\n"
    "    if(!d.alertas.length){\n"
    "      body.innerHTML = '<div style=\"text-align:center;color:#15803d;padding:40px;font-size:14px;\">&#9989; Todo en orden &mdash; sin alertas hoy</div>';\n"
    "      return;\n"
    "    }\n"
    "    var grupos = {alta:[], media:[], info:[]};\n"
    "    d.alertas.forEach(a=>grupos[a.severidad].push(a));\n"
    "    var html = '';\n"
    "    [['alta','#dc2626','&#128308; ALTA'],['media','#f59e0b','&#128993; MEDIA'],['info','#3b82f6','&#128309; INFO']].forEach(g=>{\n"
    "      if(!grupos[g[0]].length) return;\n"
    "      html += '<div style=\"margin-bottom:18px;\"><div style=\"font-size:11px;font-weight:700;color:'+g[1]+';text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;\">'+g[2]+' ('+grupos[g[0]].length+')</div>';\n"
    "      grupos[g[0]].forEach(a=>{\n"
    "        html += '<a href=\"'+(a.link||'#')+'\" style=\"display:block;text-decoration:none;background:#fafaf9;border-left:3px solid '+g[1]+';border-radius:6px;padding:10px 14px;margin-bottom:6px;color:#1c1917;\">';\n"
    "        html += '<div style=\"display:flex;justify-content:space-between;align-items:start;gap:8px;\">';\n"
    "        html += '<div style=\"flex:1;\"><div style=\"font-weight:600;font-size:13px;\">'+(a.icono||'')+' '+_esc(a.titulo)+'</div>';\n"
    "        html += '<div style=\"font-size:11px;color:#78716c;margin-top:2px;\">'+_esc(a.detalle||'')+'</div>';\n"
    "        if(a.accion) html += '<div style=\"font-size:11px;color:'+g[1]+';margin-top:3px;font-style:italic;\">&rarr; '+_esc(a.accion)+'</div>';\n"
    "        html += '</div><div style=\"font-size:10px;color:#a8a29e;text-transform:uppercase;\">'+(a.modulo||'')+'</div></div></a>';\n"
    "      });\n"
    "      html += '</div>';\n"
    "    });\n"
    "    body.innerHTML = html;\n"
    "  } catch(e){\n"
    "    body.innerHTML = '<div style=\"color:#dc2626;\">Error: '+e.message+'</div>';\n"
    "  }\n"
    "}\n"
    "refreshCampana();\n"
    "setInterval(refreshCampana, 5*60*1000);\n"
    "// PWA: registrar service worker\n"
    "if ('serviceWorker' in navigator) {\n"
    "  window.addEventListener('load', () => {\n"
    "    navigator.serviceWorker.register('/sw.js', {scope: '/'})\n"
    "      .then(reg => console.log('[PWA] SW registrado:', reg.scope))\n"
    "      .catch(err => console.warn('[PWA] SW error:', err));\n"
    "  });\n"
    "}\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
)
