MODULOS_HTML = (
    "<!DOCTYPE html>\n"
    "<html lang=\"es\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>HHA Group \u2014 M\u00f3dulos</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0;}\n"
    "body{font-family:\'Segoe UI\',sans-serif;background:#0f172a;color:#e2e8f0;min-height:100vh;}\n"
    ".header{background:#1e293b;border-bottom:1px solid #334155;padding:16px 24px;display:flex;align-items:center;justify-content:space-between;}\n"
    ".header-logo{font-size:18px;font-weight:800;color:#fff;}\n"
    ".header-sub{font-size:12px;color:#94a3b8;margin-top:2px;}\n"
    ".header-user{font-size:12px;color:#94a3b8;}\n"
    ".header-user strong{color:#e2e8f0;}\n"
    ".main{padding:28px 24px;max-width:1100px;margin:0 auto;}\n"
    ".page-title{font-size:20px;font-weight:700;color:#f1f5f9;margin-bottom:4px;}\n"
    ".page-sub{font-size:13px;color:#64748b;margin-bottom:32px;}\n"
    ".section{margin-bottom:28px;}\n"
    ".section-label{font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px;padding-bottom:6px;border-bottom:1px solid #1e293b;}\n"
    ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px;}\n"
    ".mod-card{display:flex;flex-direction:column;align-items:center;gap:8px;padding:20px 10px 16px;background:#1e293b;border:1px solid #334155;border-radius:12px;text-decoration:none;color:#e2e8f0;transition:.15s;}\n"
    ".mod-card:hover{background:#263348;border-color:#475569;transform:translateY(-2px);}\n"
    ".mod-icon{font-size:28px;line-height:1;}\n"
    ".mod-name{font-size:12px;font-weight:600;text-align:center;}\n"
    ".footer{margin-top:36px;text-align:center;}\n"
    ".logout-btn{display:inline-flex;align-items:center;gap:6px;padding:8px 20px;background:transparent;border:1px solid #334155;border-radius:8px;color:#64748b;text-decoration:none;font-size:12px;font-weight:600;transition:.15s;}\n"
    ".logout-btn:hover{border-color:#7f1d1d;color:#f87171;}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"header\">\n"
    "  <div>\n"
    "    <div class=\"header-logo\">HHA Group</div>\n"
    "    <div class=\"header-sub\">Espagiria &middot; ANIMUS Lab</div>\n"
    "  </div>\n"
    "  <div class=\"header-user\">Usuario: <strong>{usuario}</strong></div>\n"
    "</div>\n"
    "<div class=\"main\">\n"
    "  <div class=\"page-title\">&#x1F4F1; Panel de M\u00f3dulos</div>\n"
    "  <div class=\"page-sub\">Selecciona el m\u00f3dulo. Solo podr\u00e1s ingresar a los que tienes autorizaci\u00f3n.</div>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F3ED; Productivo</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/inventarios\"><span class=\"mod-icon\">&#x1F4E6;</span><span class=\"mod-name\">Planta</span></a>\n"
    "      <a class=\"mod-card\" href=\"/recepcion\"><span class=\"mod-icon\">&#x1F69A;</span><span class=\"mod-name\">Recepci\u00f3n</span></a>\n"
    "      <a class=\"mod-card\" href=\"/hub-salida\"><span class=\"mod-icon\">&#x1F9EA;</span><span class=\"mod-name\">Maquila</span></a>\n"
    "      <a class=\"mod-card\" href=\"/calidad\"><span class=\"mod-icon\">&#x1F52C;</span><span class=\"mod-name\">Calidad</span></a>\n"
    "      <a class=\"mod-card\" href=\"/tecnica\"><span class=\"mod-icon\">&#x1F527;</span><span class=\"mod-name\">T\u00e9cnica</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F6D2; Comercial</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/clientes\"><span class=\"mod-icon\">&#x1F91D;</span><span class=\"mod-name\">Clientes</span></a>\n"
    "      <a class=\"mod-card\" href=\"/compras\"><span class=\"mod-icon\">&#x1F6D2;</span><span class=\"mod-name\">Compras</span></a>\n"
    "      <a class=\"mod-card\" href=\"/solicitudes\"><span class=\"mod-icon\">&#x1F4DD;</span><span class=\"mod-name\">Solicitudes</span></a>\n"
    "      <a class=\"mod-card\" href=\"/marketing\" style=\"background:linear-gradient(135deg,rgba(99,102,241,.12),rgba(99,102,241,.04));border-color:rgba(99,102,241,.25)\"><span class=\"mod-icon\">&#x1F4E3;</span><span class=\"mod-name\" style=\"color:#818cf8\">Marketing</span></a>\n"
    "      <a class=\"mod-card\" href=\"/animus\" style=\"background:linear-gradient(135deg,rgba(212,175,55,.12),rgba(212,175,55,.04));border-color:rgba(212,175,55,.25)\"><span class=\"mod-icon\">&#x2728;</span><span class=\"mod-name\" style=\"color:#d4af37\">ÁNIMUS Lab</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F4BC; Administrativo</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/financiero\"><span class=\"mod-icon\">&#x1F4CA;</span><span class=\"mod-name\">Financiero</span></a>\n"
    "      <a class=\"mod-card\" href=\"/gerencia\"><span class=\"mod-icon\">&#x1F3DB;</span><span class=\"mod-name\">Gerencia</span></a>\n"
    "      <a class=\"mod-card\" href=\"/rrhh\"><span class=\"mod-icon\">&#x1F465;</span><span class=\"mod-name\">RRHH</span></a>\n"
    "      <a class=\"mod-card\" href=\"/compromisos\"><span class=\"mod-icon\">&#x2705;</span><span class=\"mod-name\">Compromisos</span></a>\n"
    "      <a class=\"mod-card\" href=\"/contabilidad\" style=\"background:linear-gradient(135deg,rgba(22,163,74,.12),rgba(22,163,74,.04));border-color:rgba(22,163,74,.3)\"><span class=\"mod-icon\">&#x1F4B0;</span><span class=\"mod-name\" style=\"color:#4ade80\">Contabilidad</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"footer\">\n"
    "    <a class=\"logout-btn\" href=\"/logout\">&#x23CF; Cerrar sesi\u00f3n</a>\n"
    "  </div>\n"
    "</div>\n"
    "</body>\n"
    "</html>\n"
)
