MODULOS_HTML = (
    "<!DOCTYPE html>\n"
    "<html lang=\"es\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>HHA Group \u2014 M\u00f3dulos</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0;}\n"
    "body{font-family:\'Segoe UI\',sans-serif;background:#0f172a;color:#e2e8f0;min-height:100vh;}\n"
    ".header{background:#1e293b;border-bottom:1px solid #334155;padding:16px 24px;display:flex;align-items:center;justify-content:space-between;}\n"
    ".header-logo{font-size:18px;font-weight:800;color:#fff;}\n"
    ".header-sub{font-size:12px;color:#94a3b8;margin-top:2px;}\n"
    ".header-user{font-size:12px;color:#94a3b8;}\n"
    ".header-user strong{color:#e2e8f0;}\n"
    ".main{padding:28px 24px;max-width:1100px;margin:0 auto;}\n"
    ".page-title{font-size:20px;font-weight:700;color:#f1f5f9;margin-bottom:4px;}\n"
    ".page-sub{font-size:13px;color:#64748b;margin-bottom:32px;}\n"
    ".section{margin-bottom:28px;}\n"
    ".section-label{font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px;padding-bottom:6px;border-bottom:1px solid #1e293b;}\n"
    ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px;}\n"
    ".mod-card{display:flex;flex-direction:column;align-items:center;gap:8px;padding:20px 10px 16px;background:#1e293b;border:1px solid #334155;border-radius:12px;text-decoration:none;color:#e2e8f0;transition:.15s;}\n"
    ".mod-card:hover{background:#263348;border-color:#475569;transform:translateY(-2px);}\n"
    ".mod-icon{font-size:28px;line-height:1;}\n"
    ".mod-name{font-size:12px;font-weight:600;text-align:center;}\n"
    ".footer{margin-top:36px;text-align:center;}\n"
    ".logout-btn{display:inline-flex;align-items:center;gap:6px;padding:8px 20px;background:transparent;border:1px solid #334155;border-radius:8px;color:#64748b;text-decoration:none;font-size:12px;font-weight:600;transition:.15s;}\n"
    ".logout-btn:hover{border-color:#7f1d1d;color:#f87171;}\n"
    "@media (max-width:768px){\n"
    "  .header{padding:12px 14px;flex-wrap:wrap;gap:8px;}\n"
    "  .header-logo{font-size:15px;}\n"
    "  .header-sub{font-size:10px;}\n"
    "  .main{padding:18px 14px;}\n"
    "  .page-title{font-size:17px;}\n"
    "  .page-sub{font-size:12px;margin-bottom:20px;}\n"
    "  .grid{grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:8px;}\n"
    "  .mod-card{padding:14px 6px 12px;}\n"
    "  .mod-icon{font-size:22px;}\n"
    "  .mod-name{font-size:11px;}\n"
    "  .header-user{font-size:11px;}\n"
    "}\n"
    "@media (max-width:480px){\n"
    "  .grid{grid-template-columns:repeat(3,1fr);}\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"header\">\n"
    "  <div>\n"
    "    <div class=\"header-logo\">HHA Group</div>\n"
    "    <div class=\"header-sub\">Espagiria &middot; ANIMUS Lab</div>\n"
    "  </div>\n"
    "  <div style=\"display:flex;align-items:center;gap:14px;\">\n"
    "    <button id=\"campana-btn\" onclick=\"abrirCentroNotif()\" title=\"Centro de notificaciones\" "
    "style=\"position:relative;background:transparent;border:1px solid #334155;color:#e2e8f0;"
    "border-radius:8px;width:38px;height:38px;cursor:pointer;font-size:18px;\">"
    "&#128276;<span id=\"campana-badge\" style=\"display:none;position:absolute;top:-4px;right:-4px;"
    "background:#dc2626;color:#fff;border-radius:10px;padding:1px 6px;font-size:10px;font-weight:700;\">0</span>"
    "</button>\n"
    "    <div class=\"header-user\">Usuario: <strong>{usuario}</strong></div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class=\"main\">\n"
    "  <div class=\"page-title\">&#x1F4F1; Panel de M\u00f3dulos</div>\n"
    "  <div class=\"page-sub\">Selecciona el m\u00f3dulo. Solo podr\u00e1s ingresar a los que tienes autorizaci\u00f3n.</div>\n"
    "\n"
    "  <div class=\"section\" id=\"sec-ceo\" style=\"display:none;\">\n"
    "    <div class=\"section-label\">&#x1F3AF; CEO &middot; Vista ejecutiva</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/centro\" style=\"background:linear-gradient(135deg,rgba(251,191,36,.18),rgba(251,191,36,.04));border-color:rgba(251,191,36,.4);\"><span class=\"mod-icon\">&#x1F310;</span><span class=\"mod-name\" style=\"color:#fbbf24\">Centro Operaciones</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "  <script>\n"
    "    if({usuario_es_admin}){ document.getElementById('sec-ceo').style.display=''; }\n"
    "  </script>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F3ED; Productivo</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/inventarios\"><span class=\"mod-icon\">&#x1F4E6;</span><span class=\"mod-name\">Planta</span></a>\n"
    "      <a class=\"mod-card\" href=\"/recepcion\"><span class=\"mod-icon\">&#x1F69A;</span><span class=\"mod-name\">Recepci\u00f3n</span></a>\n"
    "      <a class=\"mod-card\" href=\"/hub-salida\"><span class=\"mod-icon\">&#x1F9EA;</span><span class=\"mod-name\">Maquila</span></a>\n"
    "      <a class=\"mod-card\" href=\"/calidad\"><span class=\"mod-icon\">&#x1F52C;</span><span class=\"mod-name\">Calidad</span></a>\n"
    "      <a class=\"mod-card\" href=\"/tecnica\"><span class=\"mod-icon\">&#x1F527;</span><span class=\"mod-name\">T\u00e9cnica</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F6D2; Comercial</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/clientes\"><span class=\"mod-icon\">&#x1F91D;</span><span class=\"mod-name\">Clientes</span></a>\n"
    "      <a class=\"mod-card\" href=\"/compras\"><span class=\"mod-icon\">&#x1F6D2;</span><span class=\"mod-name\">Compras</span></a>\n"
    "      <a class=\"mod-card\" href=\"/solicitudes\"><span class=\"mod-icon\">&#x1F4DD;</span><span class=\"mod-name\">Solicitudes</span></a>\n"
    "      <a class=\"mod-card\" href=\"/marketing\" style=\"background:linear-gradient(135deg,rgba(99,102,241,.12),rgba(99,102,241,.04));border-color:rgba(99,102,241,.25)\"><span class=\"mod-icon\">&#x1F4E3;</span><span class=\"mod-name\" style=\"color:#818cf8\">Marketing</span></a>\n"
    "      <a class=\"mod-card\" href=\"/animus\" style=\"background:linear-gradient(135deg,rgba(212,175,55,.12),rgba(212,175,55,.04));border-color:rgba(212,175,55,.25)\"><span class=\"mod-icon\">&#x2728;</span><span class=\"mod-name\" style=\"color:#d4af37\">ÁNIMUS Lab</span></a>\n"
    "      <a class=\"mod-card\" href=\"/espagiria\" style=\"background:linear-gradient(135deg,rgba(14,116,144,.15),rgba(14,116,144,.04));border-color:rgba(14,116,144,.3)\"><span class=\"mod-icon\">&#x1F33F;</span><span class=\"mod-name\" style=\"color:#22d3ee\">Espagiria</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F4AC; Coordinación</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/comunicacion\" style=\"background:linear-gradient(135deg,rgba(245,158,11,.15),rgba(245,158,11,.04));border-color:rgba(245,158,11,.3)\"><span class=\"mod-icon\">&#x1F4DD;</span><span class=\"mod-name\" style=\"color:#fbbf24\">Tareas &amp; Chat</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"section\">\n"
    "    <div class=\"section-label\">&#x1F4BC; Administrativo</div>\n"
    "    <div class=\"grid\">\n"
    "      <a class=\"mod-card\" href=\"/financiero\"><span class=\"mod-icon\">&#x1F4CA;</span><span class=\"mod-name\">Financiero</span></a>\n"
    "      <a class=\"mod-card\" href=\"/gerencia\"><span class=\"mod-icon\">&#x1F3DB;</span><span class=\"mod-name\">Gerencia</span></a>\n"
    "      <a class=\"mod-card\" href=\"/rrhh\"><span class=\"mod-icon\">&#x1F465;</span><span class=\"mod-name\">RRHH</span></a>\n"
    "      <a class=\"mod-card\" href=\"/compromisos\"><span class=\"mod-icon\">&#x2705;</span><span class=\"mod-name\">Compromisos</span></a>\n"
    "      <a class=\"mod-card\" href=\"/contabilidad\" style=\"background:linear-gradient(135deg,rgba(22,163,74,.12),rgba(22,163,74,.04));border-color:rgba(22,163,74,.3)\"><span class=\"mod-icon\">&#x1F4B0;</span><span class=\"mod-name\" style=\"color:#4ade80\">Contabilidad</span></a>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class=\"footer\">\n"
    "    <a class=\"logout-btn\" href=\"/logout\">&#x23CF; Cerrar sesi\u00f3n</a>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- Modal: Centro de Notificaciones -->\n"
    "<div id=\"modal-notif\" style=\"display:none;position:fixed;inset:0;background:rgba(0,0,0,0.7);z-index:9999;align-items:flex-start;justify-content:center;padding:80px 16px 16px;\" onclick=\"if(event.target===this)cerrarCentroNotif()\">\n"
    "  <div style=\"background:#1e293b;border:1px solid #334155;border-radius:12px;width:680px;max-width:96vw;max-height:80vh;overflow-y:auto;color:#e2e8f0;\">\n"
    "    <div style=\"padding:18px 22px;border-bottom:1px solid #334155;display:flex;align-items:center;justify-content:space-between;\">\n"
    "      <div>\n"
    "        <h2 style=\"margin:0;font-size:1.15em;\">&#128276; Centro de Notificaciones</h2>\n"
    "        <div id=\"notif-stats\" style=\"font-size:11px;color:#94a3b8;margin-top:3px;\"></div>\n"
    "      </div>\n"
    "      <button onclick=\"cerrarCentroNotif()\" style=\"background:transparent;border:1px solid #475569;color:#e2e8f0;border-radius:6px;width:32px;height:32px;cursor:pointer;font-size:18px;\">&times;</button>\n"
    "    </div>\n"
    "    <div id=\"notif-body\" style=\"padding:18px 22px;\"><div style=\"text-align:center;color:#64748b;padding:40px;\">Cargando...</div></div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "function fmtCount(n){return n>9?'9+':String(n);}\n"
    "async function refreshCampana(){\n"
    "  try{\n"
    "    var r = await fetch('/api/notificaciones/count');\n"
    "    var d = await r.json();\n"
    "    var b = document.getElementById('campana-badge');\n"
    "    var btn = document.getElementById('campana-btn');\n"
    "    if(!b||!btn) return;\n"
    "    if(d.count > 0){\n"
    "      b.style.display = 'inline-block';\n"
    "      b.textContent = fmtCount(d.count);\n"
    "      btn.style.borderColor = '#dc2626';\n"
    "    } else {\n"
    "      b.style.display = 'none';\n"
    "      btn.style.borderColor = '#334155';\n"
    "    }\n"
    "  } catch(e){}\n"
    "}\n"
    "function abrirCentroNotif(){\n"
    "  var m = document.getElementById('modal-notif');\n"
    "  m.style.display = 'flex';\n"
    "  cargarNotifs();\n"
    "}\n"
    "function cerrarCentroNotif(){ document.getElementById('modal-notif').style.display = 'none'; refreshCampana(); }\n"
    "function _esc(s){return String(s||'').replace(/[<>&\"]/g, c=>({'<':'&lt;','>':'&gt;','&':'&amp;','\\\"':'&quot;'}[c]));}\n"
    "async function cargarNotifs(){\n"
    "  var body = document.getElementById('notif-body');\n"
    "  var stats = document.getElementById('notif-stats');\n"
    "  try{\n"
    "    var r = await fetch('/api/notificaciones/centro');\n"
    "    var d = await r.json();\n"
    "    if(!r.ok){ body.innerHTML='<div style=\"color:#fca5a5;\">'+_esc(d.error||'')+'</div>'; return; }\n"
    "    var ps = d.por_severidad;\n"
    "    stats.innerHTML = '&#128308; '+ps.alta+' alta &middot; &#128993; '+ps.media+' media &middot; &#128309; '+ps.info+' info';\n"
    "    if(!d.alertas.length){\n"
    "      body.innerHTML = '<div style=\"text-align:center;color:#34d399;padding:40px;font-size:14px;\">&#9989; Todo en orden &mdash; sin alertas hoy</div>';\n"
    "      return;\n"
    "    }\n"
    "    var grupos = {alta:[], media:[], info:[]};\n"
    "    d.alertas.forEach(a=>grupos[a.severidad].push(a));\n"
    "    var html = '';\n"
    "    [['alta','#7f1d1d','#fca5a5','&#128308; ALTA'],['media','#78350f','#fcd34d','&#128993; MEDIA'],['info','#1e3a8a','#93c5fd','&#128309; INFO']].forEach(g=>{\n"
    "      if(!grupos[g[0]].length) return;\n"
    "      html += '<div style=\"margin-bottom:18px;\"><div style=\"font-size:11px;font-weight:700;color:'+g[2]+';text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;\">'+g[3]+' ('+grupos[g[0]].length+')</div>';\n"
    "      grupos[g[0]].forEach(a=>{\n"
    "        html += '<a href=\"'+(a.link||'#')+'\" style=\"display:block;text-decoration:none;background:#0f172a;border-left:3px solid '+g[1]+';border-radius:6px;padding:10px 14px;margin-bottom:6px;color:#e2e8f0;\">';\n"
    "        html += '<div style=\"display:flex;justify-content:space-between;align-items:start;gap:8px;\">';\n"
    "        html += '<div style=\"flex:1;\"><div style=\"font-weight:600;font-size:13px;\">'+(a.icono||'')+' '+_esc(a.titulo)+'</div>';\n"
    "        html += '<div style=\"font-size:11px;color:#94a3b8;margin-top:2px;\">'+_esc(a.detalle||'')+'</div>';\n"
    "        if(a.accion) html += '<div style=\"font-size:11px;color:'+g[2]+';margin-top:3px;font-style:italic;\">&rarr; '+_esc(a.accion)+'</div>';\n"
    "        html += '</div><div style=\"font-size:10px;color:#64748b;text-transform:uppercase;\">'+(a.modulo||'')+'</div></div></a>';\n"
    "      });\n"
    "      html += '</div>';\n"
    "    });\n"
    "    body.innerHTML = html;\n"
    "  } catch(e){\n"
    "    body.innerHTML = '<div style=\"color:#fca5a5;\">Error: '+e.message+'</div>';\n"
    "  }\n"
    "}\n"
    "refreshCampana();\n"
    "setInterval(refreshCampana, 5*60*1000);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
)
