"""Compatibilidad SQLite -> PostgreSQL · Fase 1 de la migración.

EOS tiene ~3.700 consultas escritas con el placeholder `?` de SQLite.
PostgreSQL (driver psycopg) usa `%s`. Reescribir las 3.700 a mano sería
inviable y peligroso · en su lugar el SQL se traduce en el punto único
donde se ejecuta (el cursor adaptado de `get_db()`).

`translate_placeholders` convierte `?` -> `%s` y escapa los `%` literales
a `%%` (psycopg interpreta `%` como inicio de parámetro cuando hay args).
Respeta los `?` y `%` que están DENTRO de literales de string SQL (`'...'`),
incluyendo la comilla escapada estilo SQL (`''`).

Este módulo es PURO (sin dependencias, sin I/O) · se testea en
tests/test_pg_compat.py sin necesidad de una base de datos.
"""


import re as _re


def translate_ddl(sql: str) -> str:
    """Traduce DDL de SQLite a PostgreSQL al vuelo.

    Varios blueprints crean sus tablas bajo demanda (`CREATE TABLE IF NOT
    EXISTS ...`) con sintaxis SQLite. El adaptador pasa esos statements por
    aquí para que funcionen en Postgres (en una tabla ya existente el
    `IF NOT EXISTS` los vuelve no-op).

    Reglas: AUTOINCREMENT->IDENTITY, REAL->DOUBLE PRECISION, DATETIME->TEXT,
    datetime/date('now'[,...])->to_char(...), date(col)->substr(col,1,10),
    ALTER ... ADD COLUMN -> ADD COLUMN IF NOT EXISTS (idempotente).
    """
    s = sql
    s = _re.sub(r'INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT',
                'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
                s, flags=_re.I)
    s = _re.sub(r'\bREAL\b', 'DOUBLE PRECISION', s)
    s = _re.sub(r'\bDATETIME\b', 'TEXT', s)
    # datetime('now', '-5 hours') / '+N days' / etc.
    s = _re.sub(
        r"datetime\(\s*'now'\s*,\s*'([+-]?\d+\s*(?:hour|day|minute|month|year)s?)'\s*\)",
        r"to_char((now() + interval '\1'),'YYYY-MM-DD HH24:MI:SS')",
        s, flags=_re.I)
    s = _re.sub(r"datetime\(\s*'now'\s*,\s*'utc'\s*\)",
                "to_char((now() AT TIME ZONE 'UTC'),'YYYY-MM-DD HH24:MI:SS')",
                s, flags=_re.I)
    s = _re.sub(r"datetime\(\s*'now'\s*\)",
                "to_char(now(),'YYYY-MM-DD HH24:MI:SS')", s, flags=_re.I)
    s = _re.sub(r"date\(\s*'now'\s*\)",
                "to_char(now(),'YYYY-MM-DD')", s, flags=_re.I)
    s = _re.sub(r"\bdate\(\s*([a-z_][a-z0-9_]*)\s*\)",
                r"substr(\1,1,10)", s, flags=_re.I)
    # ALTER TABLE x ADD COLUMN y  ->  ADD COLUMN IF NOT EXISTS y
    s = _re.sub(
        r"(ALTER\s+TABLE\s+\w+\s+ADD\s+COLUMN\s+)(?!IF\s+NOT\s+EXISTS)",
        r"\1IF NOT EXISTS ", s, flags=_re.I)
    return s


def es_ddl_a_saltar(sql: str) -> bool:
    """True si el statement es DDL SQLite-only que NO aplica en Postgres
    (PRAGMA, CREATE TRIGGER) · el esquema/triggers PG se cargan aparte."""
    up = sql.lstrip().upper()
    return (up.startswith('PRAGMA')
            or up.startswith('CREATE TRIGGER')
            or up.startswith('CREATE TEMP TRIGGER')
            or up.startswith('DROP TRIGGER'))


_RE_TABLE_INFO = _re.compile(r"PRAGMA\s+table_info\s*\(\s*'?(\w+)'?\s*\)", _re.I)


def traducir_pragma(sql: str):
    """Traduce un PRAGMA de LECTURA de SQLite a la consulta Postgres
    equivalente · devuelve None si el PRAGMA no produce filas (se ignora,
    p.ej. los PRAGMA de escritura `PRAGMA journal_mode=DELETE`).
    """
    s = sql.strip()
    m = _RE_TABLE_INFO.search(s)
    if m:
        tabla = m.group(1).lower()
        return (
            "SELECT (c.ordinal_position-1) AS cid, c.column_name AS name, "
            "c.data_type AS type, "
            "CASE WHEN c.is_nullable='NO' THEN 1 ELSE 0 END AS notnull, "
            "c.column_default AS dflt_value, "
            "CASE WHEN c.column_name IN (SELECT a.attname FROM pg_index i "
            "JOIN pg_attribute a ON a.attrelid=i.indrelid "
            "AND a.attnum=ANY(i.indkey) WHERE i.indrelid="
            "('public.'||c.table_name)::regclass AND i.indisprimary) "
            "THEN 1 ELSE 0 END AS pk "
            "FROM information_schema.columns c "
            "WHERE c.table_schema='public' AND c.table_name='" + tabla + "' "
            "ORDER BY c.ordinal_position")
    up = ' '.join(s.upper().split())
    if '=' in s:
        return None                       # PRAGMA de escritura · no-op
    if up.startswith('PRAGMA JOURNAL_MODE'):
        return "SELECT 'delete' AS journal_mode"
    if up.startswith('PRAGMA INTEGRITY_CHECK'):
        return "SELECT 'ok' AS integrity_check"
    if up.startswith('PRAGMA FOREIGN_KEYS'):
        return "SELECT 1 AS foreign_keys"
    if up.startswith('PRAGMA USER_VERSION'):
        return "SELECT 0 AS user_version"
    return None                           # PRAGMA sin equivalente · no-op


def es_ddl_a_traducir(sql: str) -> bool:
    """True si el statement es DDL que hay que traducir y ejecutar."""
    up = sql.lstrip().upper()
    return (up.startswith('CREATE TABLE')
            or up.startswith('CREATE INDEX')
            or up.startswith('CREATE UNIQUE INDEX')
            or up.startswith('ALTER TABLE'))


def es_insert_or(sql: str):
    """Detecta el upsert SQLite · devuelve 'ignore', 'replace' o None.

    SQLite: `INSERT OR IGNORE` / `INSERT OR REPLACE`.
    Postgres no los tiene · se reescriben a `ON CONFLICT`.
    """
    up = sql.lstrip()[:24].upper()
    if up.startswith('INSERT OR IGNORE'):
        return 'ignore'
    if up.startswith('INSERT OR REPLACE'):
        return 'replace'
    return None


def reescribir_insert_or_ignore(sql: str) -> str:
    """`INSERT OR IGNORE INTO ...` -> `INSERT INTO ... ON CONFLICT DO NOTHING`.

    El `ON CONFLICT DO NOTHING` sin columna objetivo cubre cualquier
    restricción única, igual que el OR IGNORE de SQLite. Si la consulta
    trae `RETURNING`, el ON CONFLICT se inserta antes (orden que exige PG).
    """
    s = _re.sub(r'^(\s*)INSERT\s+OR\s+IGNORE\s+INTO\b',
                r'\1INSERT INTO', sql, count=1, flags=_re.I)
    s = s.rstrip().rstrip(';')
    m = _re.search(r'\bRETURNING\b', s, _re.I)
    if m:
        return s[:m.start()].rstrip() + ' ON CONFLICT DO NOTHING ' + s[m.start():]
    return s + ' ON CONFLICT DO NOTHING'


def _scan_top_level(s, quiero):
    """Itera (índice, char) marcando profundidad de paréntesis y strings.

    `quiero` es un callable(i, ch, depth, in_str) → si devuelve algo no-None
    el scan se detiene y lo retorna. Devuelve None si termina sin parar.
    """
    depth = 0
    in_str = False
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        if in_str:
            if ch == "'":
                if i + 1 < n and s[i + 1] == "'":
                    i += 2
                    continue
                in_str = False
        elif ch == "'":
            in_str = True
        elif ch == '-' and i + 1 < n and s[i + 1] == '-':
            # comentario de línea SQL · saltar hasta el salto de línea
            j = s.find('\n', i)
            i = n if j < 0 else j + 1
            continue
        elif ch == '/' and i + 1 < n and s[i + 1] == '*':
            # comentario de bloque · saltar hasta el cierre
            j = s.find('*/', i + 2)
            i = n if j < 0 else j + 2
            continue
        elif ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        else:
            r = quiero(i, ch, depth, in_str)
            if r is not None:
                return r
        i += 1
    return None


def _find_kw(s, kw, start=0):
    """Índice de la palabra-clave kw (mayúsculas) a profundidad 0. -1 si no."""
    klen = len(kw)
    n = len(s)

    def chk(i, ch, depth, in_str):
        if i < start or depth != 0:
            return None
        if s[i:i + klen].upper() != kw:
            return None
        before = s[i - 1] if i > 0 else ' '
        after = s[i + klen] if i + klen < n else ' '
        if (before.isalnum() or before == '_'
                or after.isalnum() or after == '_'):
            return None
        return i

    r = _scan_top_level(s, chk)
    return r if r is not None else -1


def _split_top_level(s):
    """Divide s por comas a profundidad 0 (ignora comas en () y '...')."""
    cortes = []
    _scan_top_level(s, lambda i, ch, d, st: cortes.append(i)
                     if ch == ',' and d == 0 else None)
    partes = []
    prev = 0
    for c in cortes:
        partes.append(s[prev:c])
        prev = c + 1
    partes.append(s[prev:])
    return partes


def _fin_parentesis(s, abre):
    """Dado el índice del '(' en `abre`, devuelve (idx_cierre, hay_coma_a
    profundidad 1, hay_contenido). idx_cierre = -1 si no cierra."""
    depth = 0
    in_str = False
    coma = False
    contenido = False
    i = abre
    n = len(s)
    while i < n:
        ch = s[i]
        if in_str:
            if ch == "'":
                if i + 1 < n and s[i + 1] == "'":
                    i += 2
                    continue
                in_str = False
        elif ch == "'":
            in_str = True
            contenido = True
        elif ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0:
                return i, coma, contenido
        elif ch == ',' and depth == 1:
            coma = True
        elif depth >= 1 and ch not in ' \t\r\n':
            contenido = True
        i += 1
    return -1, coma, contenido


def forzar_date_texto(sql: str) -> str:
    """Fuerza `date(X)` de 1 argumento a `date(X, '')`.

    Postgres resuelve `date(x)` de 1 argumento como el cast al tipo `date`
    (devuelve un valor date), NO la función date() de pg_functions. EOS
    trata las fechas como texto · con un 2º argumento Postgres usa la
    función date(variadic text[]) que devuelve 'YYYY-MM-DD' texto. Así no
    quedan valores tipo date y se evitan los errores `text = date`.
    """
    if 'date' not in sql.lower():
        return sql
    out = []
    i, n = 0, len(sql)
    bajo = sql.lower()
    in_str = False
    while i < n:
        ch = sql[i]
        if in_str:
            out.append(ch)
            if ch == "'":
                if i + 1 < n and sql[i + 1] == "'":
                    out.append("'")
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if ch == "'":
            in_str = True
            out.append(ch)
            i += 1
            continue
        if (bajo.startswith('date', i)
                and (i == 0 or not (sql[i - 1].isalnum() or sql[i - 1] == '_'))):
            k = i + 4
            while k < n and sql[k] in ' \t\r\n':
                k += 1
            if k < n and sql[k] == '(':
                cierre, coma, contenido = _fin_parentesis(sql, k)
                if cierre > 0 and not coma and contenido:
                    out.append(sql[i:cierre])      # 'date(...contenido'
                    out.append(", '')")
                    i = cierre + 1
                    continue
        out.append(ch)
        i += 1
    return ''.join(out)


def _kw_en(sql, idx, palabra, n):
    """¿La keyword `palabra` (mayúsculas) empieza en `idx` con límites de
    palabra a ambos lados?"""
    if sql[idx:idx + len(palabra)].upper() != palabra:
        return False
    antes = sql[idx - 1] if idx > 0 else ' '
    desp = sql[idx + len(palabra)] if idx + len(palabra) < n else ' '
    return not (antes.isalnum() or antes == '_'
                or desp.isalnum() or desp == '_')


def rewrite_having_alias(sql: str) -> str:
    """Reescribe `HAVING <alias>` (a cualquier nivel de anidación) sustituyendo
    el alias por su expresión del SELECT de su mismo scope.

    SQLite permite usar un alias del SELECT en HAVING · PostgreSQL no (solo
    en GROUP BY y ORDER BY). EOS tiene decenas de consultas con este patrón,
    muchas dentro de subconsultas (`SELECT COUNT(*) FROM (... HAVING alias)`)
    o CTEs · este reescritor las cubre en cualquier profundidad.
    """
    if 'having' not in sql.lower():
        return sql
    n = len(sql)
    # Recorrido único · pila de scopes (cada paréntesis abre uno). Cada
    # scope recuerda dónde empieza su select-list y dónde su FROM.
    pila = [{'sel': None, 'frm': None}]
    havings = []                       # (pos_HAVING, sel, frm)
    i = 0
    in_str = False
    while i < n:
        ch = sql[i]
        if in_str:
            if ch == "'":
                if i + 1 < n and sql[i + 1] == "'":
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if ch == "'":
            in_str = True
            i += 1
            continue
        if ch == '-' and i + 1 < n and sql[i + 1] == '-':
            j = sql.find('\n', i)
            i = n if j < 0 else j + 1
            continue
        if ch == '/' and i + 1 < n and sql[i + 1] == '*':
            j = sql.find('*/', i + 2)
            i = n if j < 0 else j + 2
            continue
        if ch == '(':
            pila.append({'sel': None, 'frm': None})
            i += 1
            continue
        if ch == ')':
            if len(pila) > 1:
                pila.pop()
            i += 1
            continue
        sc = pila[-1]
        if _kw_en(sql, i, 'SELECT', n) and sc['sel'] is None:
            sc['sel'] = i + 6
            i += 6
            continue
        if _kw_en(sql, i, 'FROM', n) and sc['sel'] is not None \
                and sc['frm'] is None:
            sc['frm'] = i
            i += 4
            continue
        if _kw_en(sql, i, 'HAVING', n):
            havings.append((i, sc['sel'], sc['frm']))
            i += 6
            continue
        i += 1
    if not havings:
        return sql

    def _fin_having(desde):
        """Fin de la cláusula HAVING: ORDER BY / LIMIT / UNION / cierre."""
        depth = 0
        j = desde
        s_in = False
        while j < n:
            c = sql[j]
            if s_in:
                if c == "'":
                    if j + 1 < n and sql[j + 1] == "'":
                        j += 2
                        continue
                    s_in = False
            elif c == "'":
                s_in = True
            elif c == '(':
                depth += 1
            elif c == ')':
                if depth == 0:
                    return j
                depth -= 1
            elif depth == 0 and (_kw_en(sql, j, 'ORDER', n)
                                 or _kw_en(sql, j, 'LIMIT', n)
                                 or _kw_en(sql, j, 'UNION', n)
                                 or _kw_en(sql, j, 'OFFSET', n)):
                return j
            j += 1
        return n

    resultado = sql
    # De atrás hacia adelante · no corre los índices de los HAVING previos.
    for hpos, sel, frm in sorted(havings, reverse=True):
        if sel is None or frm is None or frm <= sel:
            continue
        alias_expr = {}
        for item in _split_top_level(sql[sel:frm]):
            it = item.strip()
            m = _re.search(r'\bAS\s+"?(\w+)"?\s*$', it, _re.I)
            if m:
                alias_expr[m.group(1).lower()] = it[:m.start()].strip()
        if not alias_expr:
            continue
        fin = _fin_having(hpos + 6)

        def _repl(m, _ae=alias_expr):
            e = _ae.get(m.group(0).lower())
            return '(' + e + ')' if e else m.group(0)

        resultado = (resultado[:hpos + 6]
                     + _re.sub(r'\b\w+\b', _repl, resultado[hpos + 6:fin])
                     + resultado[fin:])
    return resultado


def translate_placeholders(sql: str) -> str:
    """Traduce SQL estilo SQLite (`?`) a estilo psycopg (`%s`).

    Reglas:
      - `?` fuera de un string literal  -> `%s`
      - `?` dentro de un string literal -> se deja igual
      - `%` en cualquier posición       -> `%%` (psycopg lo exige cuando
        la consulta lleva parámetros)

    Maneja literales `'...'` con la comilla escapada de SQL (`''`).
    No interpreta comillas dobles: en SQL estándar (y PostgreSQL) `"..."`
    delimita identificadores, no strings, y no contienen `?`/`%` relevantes.
    """
    out = []
    in_str = False          # ¿estamos dentro de un literal '...'?
    i = 0
    n = len(sql)
    while i < n:
        ch = sql[i]
        if in_str:
            if ch == "'":
                # Comilla escapada '' -> sigue dentro del string.
                if i + 1 < n and sql[i + 1] == "'":
                    out.append("''")
                    i += 2
                    continue
                in_str = False
                out.append(ch)
            elif ch == '%':
                out.append('%%')
            else:
                out.append(ch)
        else:
            if ch == "'":
                in_str = True
                out.append(ch)
            elif ch == '?':
                out.append('%s')
            elif ch == '%':
                out.append('%%')
            elif ch == '"' and i + 1 < n and sql[i + 1] == '"':
                # `""` fuera de un literal `'...'` en SQLite es un string
                # vacío · en PostgreSQL `""` sería un identificador vacío
                # (inválido). Lo traducimos a `''` (string vacío SQL estándar).
                # Sebastián 19-may-2026: vino del bug "Sin producciones
                # registradas" en el historial · el COALESCE(col,"") rompía.
                out.append("''")
                i += 2
                continue
            else:
                out.append(ch)
        i += 1
    return ''.join(out)
